#!/bin/bash

# Interview Generation Controller Test Script
# This script demonstrates the new generation endpoints separated from the main interview prep controller

BASE_URL="http://localhost:8085/tymbl-service"
GENERATION_API_BASE="$BASE_URL/api/v1/interview-generation"
PREP_API_BASE="$BASE_URL/api/v1/interview-prep"

echo "=== Interview Generation Controller Test ==="
echo "Base URL: $BASE_URL"
echo "Generation API Base: $GENERATION_API_BASE"
echo "Prep API Base: $PREP_API_BASE"
echo ""

echo "=== Topic Generation Endpoints ==="
echo ""

echo "1. Generate Topics for Specific Designation"
echo "POST $GENERATION_API_BASE/designations/Software%20Engineer/topics/generate"
echo "Expected: 10 AI-generated topics for Software Engineer"
echo ""

echo "2. Generate and Save Topics for Specific Designation"
echo "POST $GENERATION_API_BASE/designations/Data%20Scientist/topics/generate-and-save"
echo "Expected: Generate topics and save them to database"
echo ""

echo "3. Generate Topics for All Designations"
echo "POST $GENERATION_API_BASE/designations/topics/generate-all"
echo "Expected: Generate topics for all designations in database"
echo ""

echo "4. Generate and Save Topics for All Designations"
echo "POST $GENERATION_API_BASE/designations/topics/generate-and-save-all"
echo "Expected: Generate and save topics for all designations"
echo ""

echo "=== Question Generation Endpoints ==="
echo ""

echo "5. Request Question Generation (General)"
echo "POST $GENERATION_API_BASE/questions/generate"
echo "Content-Type: application/json"
echo "Body: {"
echo "  \"requestType\": \"GENERAL\","
echo "  \"designation\": \"Software Engineer\","
echo "  \"topicName\": \"Data Structures & Algorithms\","
echo "  \"difficultyLevel\": \"INTERMEDIATE\","
echo "  \"numQuestions\": 5"
echo "}"
echo ""

echo "6. Request Question Generation (Company-Specific)"
echo "POST $GENERATION_API_BASE/questions/generate"
echo "Content-Type: application/json"
echo "Body: {"
echo "  \"requestType\": \"COMPANY_SPECIFIC\","
echo "  \"designation\": \"Software Engineer\","
echo "  \"companyName\": \"Google\","
echo "  \"topicName\": \"System Design\","
echo "  \"difficultyLevel\": \"ADVANCED\","
echo "  \"numQuestions\": 3"
echo "}"
echo ""

echo "7. Check Generation Status"
echo "GET $GENERATION_API_BASE/questions/generation/queue/{queueId}"
echo "Expected: Status of the generation request"
echo ""

echo "8. Get Pending Requests"
echo "GET $GENERATION_API_BASE/questions/generation/queue/pending"
echo "Expected: List of pending generation requests"
echo ""

echo "9. Get In-Progress Requests"
echo "GET $GENERATION_API_BASE/questions/generation/queue/in-progress"
echo "Expected: List of in-progress generation requests"
echo ""

echo "=== Sample cURL Commands (with authentication) ==="
echo ""
echo "# Generate topics for Software Engineer"
echo "curl -X POST \"$GENERATION_API_BASE/designations/Software%20Engineer/topics/generate\" \\"
echo "  -H \"Authorization: Bearer YOUR_JWT_TOKEN\""
echo ""
echo "# Generate and save topics for Data Scientist"
echo "curl -X POST \"$GENERATION_API_BASE/designations/Data%20Scientist/topics/generate-and-save\" \\"
echo "  -H \"Authorization: Bearer YOUR_JWT_TOKEN\""
echo ""
echo "# Generate topics for all designations"
echo "curl -X POST \"$GENERATION_API_BASE/designations/topics/generate-all\" \\"
echo "  -H \"Authorization: Bearer YOUR_JWT_TOKEN\""
echo ""
echo "# Request general question generation"
echo "curl -X POST \"$GENERATION_API_BASE/questions/generate\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"Authorization: Bearer YOUR_JWT_TOKEN\" \\"
echo "  -d '{"
echo "    \"requestType\": \"GENERAL\","
echo "    \"designation\": \"Software Engineer\","
echo "    \"topicName\": \"Data Structures & Algorithms\","
echo "    \"difficultyLevel\": \"INTERMEDIATE\","
echo "    \"numQuestions\": 5"
echo "  }'"
echo ""
echo "# Check generation status"
echo "curl -X GET \"$GENERATION_API_BASE/questions/generation/queue/1\" \\"
echo "  -H \"Authorization: Bearer YOUR_JWT_TOKEN\""
echo ""

echo "=== Content Retrieval Endpoints (Interview Prep Controller) ==="
echo ""
echo "# Get all designations from database"
echo "curl -X GET \"$PREP_API_BASE/designations/database\" \\"
echo "  -H \"Authorization: Bearer YOUR_JWT_TOKEN\""
echo ""
echo "# Get topics for Software Engineer"
echo "curl -X GET \"$PREP_API_BASE/designations/Software%20Engineer/topics\" \\"
echo "  -H \"Authorization: Bearer YOUR_JWT_TOKEN\""
echo ""
echo "# Get general questions for Software Engineer"
echo "curl -X GET \"$PREP_API_BASE/designations/Software%20Engineer/questions/general\" \\"
echo "  -H \"Authorization: Bearer YOUR_JWT_TOKEN\""
echo ""
echo "# Get company questions for Google"
echo "curl -X GET \"$PREP_API_BASE/companies/Google/designations/Software%20Engineer/questions\" \\"
echo "  -H \"Authorization: Bearer YOUR_JWT_TOKEN\""
echo ""

echo "=== Controller Separation Benefits ==="
echo "✅ Generation endpoints separated from content retrieval"
echo "✅ Clear API organization and responsibility"
echo "✅ Easier to manage and maintain"
echo "✅ Better separation of concerns"
echo "✅ Generation-specific error handling"
echo "✅ Dedicated generation documentation"
echo ""

echo "=== API Structure ==="
echo ""
echo "Interview Preparation Controller (/api/v1/interview-prep):"
echo "- Content retrieval and management"
echo "- Topic listing and filtering"
echo "- Question retrieval (general and company-specific)"
echo "- Statistics and analytics"
echo ""
echo "Interview Generation Controller (/api/v1/interview-generation):"
echo "- AI-powered topic generation"
echo "- AI-powered question generation"
echo "- Generation queue management"
echo "- Generation status tracking"
echo ""

echo "Test script completed!" 