#!/bin/bash

# Topic Generation Test Script
# This script demonstrates the new GenAI-powered topic generation for designations

BASE_URL="http://localhost:8085/tymbl-service"
API_BASE="$BASE_URL/api/v1/interview-prep"

echo "=== Topic Generation System Test ==="
echo "Base URL: $BASE_URL"
echo "API Base: $API_BASE"
echo ""

echo "1. Get All Designations from Database"
echo "GET $API_BASE/designations/database"
echo "Expected: List of all designations from the designation table"
echo ""

echo "2. Generate Topics for Specific Designation"
echo "POST $API_BASE/designations/Software%20Engineer/topics/generate"
echo "Expected: 10 AI-generated topics for Software Engineer"
echo ""

echo "3. Generate and Save Topics for Specific Designation"
echo "POST $API_BASE/designations/Data%20Scientist/topics/generate-and-save"
echo "Expected: Generate topics and save them to database"
echo ""

echo "4. Generate Topics for All Designations"
echo "POST $API_BASE/designations/topics/generate-all"
echo "Expected: Generate topics for all designations in database"
echo ""

echo "5. Generate and Save Topics for All Designations"
echo "POST $API_BASE/designations/topics/generate-and-save-all"
echo "Expected: Generate and save topics for all designations"
echo ""

echo "=== Sample cURL Commands (with authentication) ==="
echo ""
echo "# Get all designations from database"
echo "curl -X GET \"$API_BASE/designations/database\" \\"
echo "  -H \"Authorization: Bearer YOUR_JWT_TOKEN\""
echo ""
echo "# Generate topics for Software Engineer"
echo "curl -X POST \"$API_BASE/designations/Software%20Engineer/topics/generate\" \\"
echo "  -H \"Authorization: Bearer YOUR_JWT_TOKEN\""
echo ""
echo "# Generate and save topics for Data Scientist"
echo "curl -X POST \"$API_BASE/designations/Data%20Scientist/topics/generate-and-save\" \\"
echo "  -H \"Authorization: Bearer YOUR_JWT_TOKEN\""
echo ""
echo "# Generate topics for all designations"
echo "curl -X POST \"$API_BASE/designations/topics/generate-all\" \\"
echo "  -H \"Authorization: Bearer YOUR_JWT_TOKEN\""
echo ""
echo "# Generate and save topics for all designations"
echo "curl -X POST \"$API_BASE/designations/topics/generate-and-save-all\" \\"
echo "  -H \"Authorization: Bearer YOUR_JWT_TOKEN\""
echo ""

echo "=== Expected Response Format ==="
echo ""
echo "Topic Generation Response:"
echo "{"
echo "  \"designation\": \"Software Engineer\","
echo "  \"topics_count\": 10,"
echo "  \"topics\": ["
echo "    {"
echo "      \"topic_name\": \"Java Programming\","
echo "      \"topic_description\": \"Core Java concepts essential for software development\","
echo "      \"difficulty_level\": \"INTERMEDIATE\","
echo "      \"category\": \"TECHNICAL\","
echo "      \"estimated_prep_time_hours\": 20"
echo "    },"
echo "    {"
echo "      \"topic_name\": \"System Design\","
echo "      \"topic_description\": \"Scalable architecture and distributed systems\","
echo "      \"difficulty_level\": \"ADVANCED\","
echo "      \"category\": \"TECHNICAL\","
echo "      \"estimated_prep_time_hours\": 30"
echo "    }"
echo "  ],"
echo "  \"message\": \"Topics generated successfully using GenAI\""
echo "}"
echo ""

echo "=== GenAI Features ==="
echo "✅ Generates exactly 10 topics per designation"
echo "✅ Includes both technical and non-technical skills"
echo "✅ Technical skills: Programming languages, frameworks, tools"
echo "✅ Non-technical skills: Soft skills, management, business skills"
echo "✅ Categorizes topics: TECHNICAL, BEHAVIORAL, PRODUCT"
echo "✅ Assigns difficulty levels: BEGINNER, INTERMEDIATE, ADVANCED"
echo "✅ Estimates preparation time in hours"
echo "✅ Provides detailed descriptions for each topic"
echo "✅ Can save generated topics to database"
echo "✅ Supports batch generation for all designations"
echo ""

echo "=== Example Topics by Designation ==="
echo ""
echo "Software Engineer:"
echo "- Java, Python, System Design, Agile Methodologies, Problem Solving"
echo ""
echo "Engineering Manager:"
echo "- Stakeholder Management, Team Leadership, Technical Architecture, Project Management"
echo ""
echo "Data Scientist:"
echo "- Machine Learning, Python, Statistical Analysis, Data Visualization, Business Acumen"
echo ""
echo "Product Manager:"
echo "- Product Strategy, User Research, Data Analysis, Stakeholder Management, Agile"
echo ""

echo "=== Key Benefits ==="
echo "✅ AI-powered topic generation using Gemini"
echo "✅ Automatic skill identification for any designation"
echo "✅ Both technical and non-technical skill coverage"
echo "✅ Real-time generation or batch processing"
echo "✅ Database integration for persistence"
echo "✅ Comprehensive topic descriptions"
echo "✅ Difficulty and time estimation"
echo "✅ Category classification"
echo ""

echo "Test script completed!" 