-- Add similar skills columns to skills table
-- This script adds columns for storing similar skills generated by GenAI

-- Add similar_skills_by_name column to store comma-separated similar skill names
ALTER TABLE skills ADD COLUMN IF NOT EXISTS similar_skills_by_name TEXT;

-- Add similar_skills_by_id column to store comma-separated similar skill IDs (for future use)
ALTER TABLE skills ADD COLUMN IF NOT EXISTS similar_skills_by_id TEXT;

-- Add a flag to track if similar skills have been generated
ALTER TABLE skills ADD COLUMN IF NOT EXISTS similar_skills_processed BOOLEAN DEFAULT FALSE;

-- Add index for better performance when querying processed skills
CREATE INDEX IF NOT EXISTS idx_skills_similar_skills_processed ON skills(similar_skills_processed);

-- Add index for better performance when searching by similar skills
CREATE INDEX IF NOT EXISTS idx_skills_similar_skills_by_name ON skills USING GIN(to_tsvector('english', similar_skills_by_name));

-- Update existing skills to mark them as not processed (so they can be processed by the new service)
UPDATE skills SET similar_skills_processed = FALSE WHERE similar_skills_processed IS NULL;

-- Add comment to document the purpose of these columns
COMMENT ON COLUMN skills.similar_skills_by_name IS 'Comma-separated list of similar skill names generated by GenAI';
COMMENT ON COLUMN skills.similar_skills_by_id IS 'Comma-separated list of similar skill IDs (for future use)';
COMMENT ON COLUMN skills.similar_skills_processed IS 'Flag indicating whether similar skills have been generated for this skill';
