-- Insert cities for India
INSERT INTO cities (id, name, state, country) VALUES
-- Andhra Pradesh
(1, 'Visakhapatnam', 'Andhra Pradesh', 'India'),
(2, 'Vijayawada', 'Andhra Pradesh', 'India'),
(3, 'Guntur', 'Andhra Pradesh', 'India'),
(4, 'Nellore', 'Andhra Pradesh', 'India'),
(5, 'Kurnool', 'Andhra Pradesh', 'India'),
(6, 'Tirupati', 'Andhra Pradesh', 'India'),
(7, 'Kurnool', 'Andhra Pradesh', 'India'),
(8, 'Kadapa', 'Andhra Pradesh', 'India'),
(9, 'Anantapur', 'Andhra Pradesh', 'India'),
(10, 'Kakinada', 'Andhra Pradesh', 'India'),

-- Arunachal Pradesh
(11, 'Itanagar', 'Arunachal Pradesh', 'India'),
(12, 'Naharlagun', 'Arunachal Pradesh', 'India'),
(13, 'Pasighat', 'Arunachal Pradesh', 'India'),
(14, 'Tawang', 'Arunachal Pradesh', 'India'),
(15, 'Bomdila', 'Arunachal Pradesh', 'India'),

-- Assam
(16, 'Guwahati', 'Assam', 'India'),
(17, 'Silchar', 'Assam', 'India'),
(18, 'Dibrugarh', 'Assam', 'India'),
(19, 'Jorhat', 'Assam', 'India'),
(20, 'Nagaon', 'Assam', 'India'),
(21, 'Tinsukia', 'Assam', 'India'),
(22, 'Tezpur', 'Assam', 'India'),
(23, 'Barpeta', 'Assam', 'India'),
(24, 'Goalpara', 'Assam', 'India'),
(25, 'Bongaigaon', 'Assam', 'India'),

-- Bihar
(26, 'Patna', 'Bihar', 'India'),
(27, 'Gaya', 'Bihar', 'India'),
(28, 'Muzaffarpur', 'Bihar', 'India'),
(29, 'Bhagalpur', 'Bihar', 'India'),
(30, 'Darbhanga', 'Bihar', 'India'),
(31, 'Purnia', 'Bihar', 'India'),
(32, 'Arrah', 'Bihar', 'India'),
(33, 'Bihar Sharif', 'Bihar', 'India'),
(34, 'Begusarai', 'Bihar', 'India'),
(35, 'Katihar', 'Bihar', 'India'),

-- Chhattisgarh
(36, 'Raipur', 'Chhattisgarh', 'India'),
(37, 'Bhilai', 'Chhattisgarh', 'India'),
(38, 'Korba', 'Chhattisgarh', 'India'),
(39, 'Bilaspur', 'Chhattisgarh', 'India'),
(40, 'Jagdalpur', 'Chhattisgarh', 'India'),
(41, 'Raigarh', 'Chhattisgarh', 'India'),
(42, 'Ambikapur', 'Chhattisgarh', 'India'),
(43, 'Mahasamund', 'Chhattisgarh', 'India'),
(44, 'Dhamtari', 'Chhattisgarh', 'India'),
(45, 'Chirmiri', 'Chhattisgarh', 'India'),

-- Delhi
(46, 'New Delhi', 'Delhi', 'India'),
(47, 'North Delhi', 'Delhi', 'India'),
(48, 'South Delhi', 'Delhi', 'India'),
(49, 'East Delhi', 'Delhi', 'India'),
(50, 'West Delhi', 'Delhi', 'India'),
(51, 'Central Delhi', 'Delhi', 'India'),
(52, 'Northeast Delhi', 'Delhi', 'India'),
(53, 'Northwest Delhi', 'Delhi', 'India'),
(54, 'Shahdara', 'Delhi', 'India'),
(55, 'Southwest Delhi', 'Delhi', 'India'),

-- Goa
(56, 'Panaji', 'Goa', 'India'),
(57, 'Margao', 'Goa', 'India'),
(58, 'Vasco da Gama', 'Goa', 'India'),
(59, 'Ponda', 'Goa', 'India'),
(60, 'Bicholim', 'Goa', 'India'),
(61, 'Canacona', 'Goa', 'India'),
(62, 'Quepem', 'Goa', 'India'),
(63, 'Sanguem', 'Goa', 'India'),
(64, 'Sattari', 'Goa', 'India'),
(65, 'Salcete', 'Goa', 'India'),

-- Gujarat
(66, 'Ahmedabad', 'Gujarat', 'India'),
(67, 'Surat', 'Gujarat', 'India'),
(68, 'Vadodara', 'Gujarat', 'India'),
(69, 'Rajkot', 'Gujarat', 'India'),
(70, 'Bhavnagar', 'Gujarat', 'India'),
(71, 'Jamnagar', 'Gujarat', 'India'),
(72, 'Junagadh', 'Gujarat', 'India'),
(73, 'Anand', 'Gujarat', 'India'),
(74, 'Navsari', 'Gujarat', 'India'),
(75, 'Morbi', 'Gujarat', 'India'),

-- Haryana
(76, 'Gurgaon', 'Haryana', 'India'),
(77, 'Faridabad', 'Haryana', 'India'),
(78, 'Panipat', 'Haryana', 'India'),
(79, 'Ambala', 'Haryana', 'India'),
(80, 'Yamunanagar', 'Haryana', 'India'),
(81, 'Rohtak', 'Haryana', 'India'),
(82, 'Hisar', 'Haryana', 'India'),
(83, 'Karnal', 'Haryana', 'India'),
(84, 'Sonipat', 'Haryana', 'India'),
(85, 'Sirsa', 'Haryana', 'India'),

-- Himachal Pradesh
(86, 'Shimla', 'Himachal Pradesh', 'India'),
(87, 'Dharamshala', 'Himachal Pradesh', 'India'),
(88, 'Manali', 'Himachal Pradesh', 'India'),
(89, 'Kullu', 'Himachal Pradesh', 'India'),
(90, 'Dalhousie', 'Himachal Pradesh', 'India'),
(91, 'Kasauli', 'Himachal Pradesh', 'India'),
(92, 'Mandi', 'Himachal Pradesh', 'India'),
(93, 'Palampur', 'Himachal Pradesh', 'India'),
(94, 'Chamba', 'Himachal Pradesh', 'India'),
(95, 'Kangra', 'Himachal Pradesh', 'India'),

-- Jammu and Kashmir
(96, 'Srinagar', 'Jammu and Kashmir', 'India'),
(97, 'Jammu', 'Jammu and Kashmir', 'India'),
(98, 'Baramulla', 'Jammu and Kashmir', 'India'),
(99, 'Anantnag', 'Jammu and Kashmir', 'India'),
(100, 'Pulwama', 'Jammu and Kashmir', 'India'),
(101, 'Kupwara', 'Jammu and Kashmir', 'India'),
(102, 'Budgam', 'Jammu and Kashmir', 'India'),
(103, 'Ganderbal', 'Jammu and Kashmir', 'India'),
(104, 'Shopian', 'Jammu and Kashmir', 'India'),
(105, 'Bandipora', 'Jammu and Kashmir', 'India'),

-- Jharkhand
(106, 'Ranchi', 'Jharkhand', 'India'),
(107, 'Jamshedpur', 'Jharkhand', 'India'),
(108, 'Dhanbad', 'Jharkhand', 'India'),
(109, 'Bokaro', 'Jharkhand', 'India'),
(110, 'Deoghar', 'Jharkhand', 'India'),
(111, 'Hazaribagh', 'Jharkhand', 'India'),
(112, 'Giridih', 'Jharkhand', 'India'),
(113, 'Dumka', 'Jharkhand', 'India'),
(114, 'Phusro', 'Jharkhand', 'India'),
(115, 'Adityapur', 'Jharkhand', 'India'),

-- Karnataka
(116, 'Bangalore', 'Karnataka', 'India'),
(117, 'Mysore', 'Karnataka', 'India'),
(118, 'Hubli', 'Karnataka', 'India'),
(119, 'Mangalore', 'Karnataka', 'India'),
(120, 'Belgaum', 'Karnataka', 'India'),
(121, 'Gulbarga', 'Karnataka', 'India'),
(122, 'Davanagere', 'Karnataka', 'India'),
(123, 'Bellary', 'Karnataka', 'India'),
(124, 'Bijapur', 'Karnataka', 'India'),
(125, 'Hassan', 'Karnataka', 'India'),

-- Kerala
(126, 'Thiruvananthapuram', 'Kerala', 'India'),
(127, 'Kochi', 'Kerala', 'India'),
(128, 'Kozhikode', 'Kerala', 'India'),
(129, 'Thrissur', 'Kerala', 'India'),
(130, 'Kollam', 'Kerala', 'India'),
(131, 'Alappuzha', 'Kerala', 'India'),
(132, 'Kannur', 'Kerala', 'India'),
(133, 'Kasaragod', 'Kerala', 'India'),
(134, 'Kottayam', 'Kerala', 'India'),
(135, 'Palakkad', 'Kerala', 'India'),

-- Madhya Pradesh
(136, 'Bhopal', 'Madhya Pradesh', 'India'),
(137, 'Indore', 'Madhya Pradesh', 'India'),
(138, 'Jabalpur', 'Madhya Pradesh', 'India'),
(139, 'Gwalior', 'Madhya Pradesh', 'India'),
(140, 'Ujjain', 'Madhya Pradesh', 'India'),
(141, 'Sagar', 'Madhya Pradesh', 'India'),
(142, 'Dewas', 'Madhya Pradesh', 'India'),
(143, 'Satna', 'Madhya Pradesh', 'India'),
(144, 'Ratlam', 'Madhya Pradesh', 'India'),
(145, 'Murwara', 'Madhya Pradesh', 'India'),

-- Maharashtra
(146, 'Mumbai', 'Maharashtra', 'India'),
(147, 'Pune', 'Maharashtra', 'India'),
(148, 'Nagpur', 'Maharashtra', 'India'),
(149, 'Thane', 'Maharashtra', 'India'),
(150, 'Nashik', 'Maharashtra', 'India'),
(151, 'Kalyan-Dombivli', 'Maharashtra', 'India'),
(152, 'Vasai-Virar', 'Maharashtra', 'India'),
(153, 'Solapur', 'Maharashtra', 'India'),
(154, 'Mira-Bhayandar', 'Maharashtra', 'India'),
(155, 'Bhiwandi', 'Maharashtra', 'India'),

-- Manipur
(156, 'Imphal', 'Manipur', 'India'),
(157, 'Thoubal', 'Manipur', 'India'),
(158, 'Bishnupur', 'Manipur', 'India'),
(159, 'Churachandpur', 'Manipur', 'India'),
(160, 'Kakching', 'Manipur', 'India'),
(161, 'Lilong', 'Manipur', 'India'),
(162, 'Mayang Imphal', 'Manipur', 'India'),
(163, 'Moirang', 'Manipur', 'India'),
(164, 'Nambol', 'Manipur', 'India'),
(165, 'Oinam', 'Manipur', 'India'),

-- Meghalaya
(166, 'Shillong', 'Meghalaya', 'India'),
(167, 'Tura', 'Meghalaya', 'India'),
(168, 'Nongstoin', 'Meghalaya', 'India'),
(169, 'Jowai', 'Meghalaya', 'India'),
(170, 'Nongpoh', 'Meghalaya', 'India'),
(171, 'Williamnagar', 'Meghalaya', 'India'),
(172, 'Baghmara', 'Meghalaya', 'India'),
(173, 'Resubelpara', 'Meghalaya', 'India'),
(174, 'Mairang', 'Meghalaya', 'India'),
(175, 'Mawkyrwat', 'Meghalaya', 'India'),

-- Mizoram
(176, 'Aizawl', 'Mizoram', 'India'),
(177, 'Lunglei', 'Mizoram', 'India'),
(178, 'Saiha', 'Mizoram', 'India'),
(179, 'Champhai', 'Mizoram', 'India'),
(180, 'Kolasib', 'Mizoram', 'India'),
(181, 'Serchhip', 'Mizoram', 'India'),
(182, 'Lawngtlai', 'Mizoram', 'India'),
(183, 'Mamit', 'Mizoram', 'India'),
(184, 'Hnahthial', 'Mizoram', 'India'),
(185, 'Saitual', 'Mizoram', 'India'),

-- Nagaland
(186, 'Kohima', 'Nagaland', 'India'),
(187, 'Dimapur', 'Nagaland', 'India'),
(188, 'Mokokchung', 'Nagaland', 'India'),
(189, 'Tuensang', 'Nagaland', 'India'),
(190, 'Wokha', 'Nagaland', 'India'),
(191, 'Zunheboto', 'Nagaland', 'India'),
(192, 'Phek', 'Nagaland', 'India'),
(193, 'Kiphire', 'Nagaland', 'India'),
(194, 'Longleng', 'Nagaland', 'India'),
(195, 'Noklak', 'Nagaland', 'India'),

-- Odisha
(196, 'Bhubaneswar', 'Odisha', 'India'),
(197, 'Cuttack', 'Odisha', 'India'),
(198, 'Puri', 'Odisha', 'India'),
(199, 'Rourkela', 'Odisha', 'India'),
(200, 'Sambalpur', 'Odisha', 'India'),
(201, 'Brahmapur', 'Odisha', 'India'),
(202, 'Baleshwar', 'Odisha', 'India'),
(203, 'Baripada', 'Odisha', 'India'),
(204, 'Bhadrak', 'Odisha', 'India'),
(205, 'Balangir', 'Odisha', 'India'),

-- Punjab
(206, 'Chandigarh', 'Punjab', 'India'),
(207, 'Ludhiana', 'Punjab', 'India'),
(208, 'Amritsar', 'Punjab', 'India'),
(209, 'Jalandhar', 'Punjab', 'India'),
(210, 'Patiala', 'Punjab', 'India'),
(211, 'Bathinda', 'Punjab', 'India'),
(212, 'Pathankot', 'Punjab', 'India'),
(213, 'Hoshiarpur', 'Punjab', 'India'),
(214, 'Moga', 'Punjab', 'India'),
(215, 'Firozpur', 'Punjab', 'India'),

-- Rajasthan
(216, 'Jaipur', 'Rajasthan', 'India'),
(217, 'Jodhpur', 'Rajasthan', 'India'),
(218, 'Udaipur', 'Rajasthan', 'India'),
(219, 'Kota', 'Rajasthan', 'India'),
(220, 'Bikaner', 'Rajasthan', 'India'),
(221, 'Ajmer', 'Rajasthan', 'India'),
(222, 'Alwar', 'Rajasthan', 'India'),
(223, 'Bhilwara', 'Rajasthan', 'India'),
(224, 'Bharatpur', 'Rajasthan', 'India'),
(225, 'Sri Ganganagar', 'Rajasthan', 'India'),

-- Sikkim
(226, 'Gangtok', 'Sikkim', 'India'),
(227, 'Namchi', 'Sikkim', 'India'),
(228, 'Mangan', 'Sikkim', 'India'),
(229, 'Jorethang', 'Sikkim', 'India'),
(230, 'Rangpo', 'Sikkim', 'India'),
(231, 'Singtam', 'Sikkim', 'India'),
(232, 'Gyalshing', 'Sikkim', 'India'),
(233, 'Pakyong', 'Sikkim', 'India'),
(234, 'Ravongla', 'Sikkim', 'India'),
(235, 'Lachen', 'Sikkim', 'India'),

-- Tamil Nadu
(236, 'Chennai', 'Tamil Nadu', 'India'),
(237, 'Coimbatore', 'Tamil Nadu', 'India'),
(238, 'Madurai', 'Tamil Nadu', 'India'),
(239, 'Salem', 'Tamil Nadu', 'India'),
(240, 'Tiruchirappalli', 'Tamil Nadu', 'India'),
(241, 'Tirunelveli', 'Tamil Nadu', 'India'),
(242, 'Thoothukudi', 'Tamil Nadu', 'India'),
(243, 'Thanjavur', 'Tamil Nadu', 'India'),
(244, 'Tiruvannamalai', 'Tamil Nadu', 'India'),
(245, 'Cuddalore', 'Tamil Nadu', 'India'),

-- Telangana
(246, 'Hyderabad', 'Telangana', 'India'),
(247, 'Warangal', 'Telangana', 'India'),
(248, 'Nizamabad', 'Telangana', 'India'),
(249, 'Karimnagar', 'Telangana', 'India'),
(250, 'Ramagundam', 'Telangana', 'India'),
(251, 'Khammam', 'Telangana', 'India'),
(252, 'Mahbubnagar', 'Telangana', 'India'),
(253, 'Nalgonda', 'Telangana', 'India'),
(254, 'Adilabad', 'Telangana', 'India'),
(255, 'Siddipet', 'Telangana', 'India'),

-- Tripura
(256, 'Agartala', 'Tripura', 'India'),
(257, 'Udaipur', 'Tripura', 'India'),
(258, 'Dharmanagar', 'Tripura', 'India'),
(259, 'Ambassa', 'Tripura', 'India'),
(260, 'Kailasahar', 'Tripura', 'India'),
(261, 'Belonia', 'Tripura', 'India'),
(262, 'Khowai', 'Tripura', 'India'),
(263, 'Teliamura', 'Tripura', 'India'),
(264, 'Sabroom', 'Tripura', 'India'),
(265, 'Amarpur', 'Tripura', 'India'),

-- Uttar Pradesh
(266, 'Lucknow', 'Uttar Pradesh', 'India'),
(267, 'Kanpur', 'Uttar Pradesh', 'India'),
(268, 'Agra', 'Uttar Pradesh', 'India'),
(269, 'Varanasi', 'Uttar Pradesh', 'India'),
(270, 'Prayagraj', 'Uttar Pradesh', 'India'),
(271, 'Noida', 'Uttar Pradesh', 'India'),
(272, 'Ghaziabad', 'Uttar Pradesh', 'India'),
(273, 'Meerut', 'Uttar Pradesh', 'India'),
(274, 'Bareilly', 'Uttar Pradesh', 'India'),
(275, 'Aligarh', 'Uttar Pradesh', 'India'),

-- Uttarakhand
(276, 'Dehradun', 'Uttarakhand', 'India'),
(277, 'Haridwar', 'Uttarakhand', 'India'),
(278, 'Rishikesh', 'Uttarakhand', 'India'),
(279, 'Haldwani', 'Uttarakhand', 'India'),
(280, 'Roorkee', 'Uttarakhand', 'India'),
(281, 'Kashipur', 'Uttarakhand', 'India'),
(282, 'Rudrapur', 'Uttarakhand', 'India'),
(283, 'Kotdwara', 'Uttarakhand', 'India'),
(284, 'Mussoorie', 'Uttarakhand', 'India'),
(285, 'Nainital', 'Uttarakhand', 'India'),

-- West Bengal
(286, 'Kolkata', 'West Bengal', 'India'),
(287, 'Howrah', 'West Bengal', 'India'),
(288, 'Durgapur', 'West Bengal', 'India'),
(289, 'Asansol', 'West Bengal', 'India'),
(290, 'Siliguri', 'West Bengal', 'India'),
(291, 'Darjeeling', 'West Bengal', 'India'),
(292, 'Bardhaman', 'West Bengal', 'India'),
(293, 'Malda', 'West Bengal', 'India'),
(294, 'Baharampur', 'West Bengal', 'India'),
(295, 'Habra', 'West Bengal', 'India'); 