-- SQL script to populate the companies table with major tech companies for interview preparation
-- These INSERT statements will add companies with their basic information

-- Disable foreign key checks
SET FOREIGN_KEY_CHECKS = 0;

-- Clear existing data
TRUNCATE TABLE companies;
ALTER TABLE companies AUTO_INCREMENT = 1;

-- Enable foreign key checks
SET FOREIGN_KEY_CHECKS = 1;

-- Insert technology companies
INSERT IGNORE INTO companies (name, description, website, logo_url) VALUES
('Google', 'A multinational technology company that specializes in Internet-related services and products.', 'https://www.google.com', 'https://logo.clearbit.com/google.com'),
('Amazon', 'An American multinational technology company focusing on e-commerce, cloud computing, digital streaming, and artificial intelligence.', 'https://www.amazon.com', 'https://logo.clearbit.com/amazon.com'),
('Microsoft', 'An American multinational technology corporation that produces computer software, consumer electronics, personal computers, and related services.', 'https://www.microsoft.com', 'https://logo.clearbit.com/microsoft.com'),
('Apple', 'An American multinational technology company that specializes in consumer electronics, software and online services.', 'https://www.apple.com', 'https://logo.clearbit.com/apple.com'),
('Facebook', 'An American social media and technology company', 'https://www.facebook.com', 'https://logo.clearbit.com/facebook.com'),
('Netflix', 'An American subscription streaming service and production company.', 'https://www.netflix.com', 'https://logo.clearbit.com/netflix.com'),
('Twitter', 'An American microblogging and social networking service.', 'https://www.twitter.com', 'https://logo.clearbit.com/twitter.com'),
('LinkedIn', 'A business and employment-focused social media platform.', 'https://www.linkedin.com', 'https://logo.clearbit.com/linkedin.com'),
('Salesforce', 'An American cloud-based software company that provides customer relationship management service.', 'https://www.salesforce.com', 'https://logo.clearbit.com/salesforce.com'),
('Oracle', 'An American multinational computer technology corporation.', 'https://www.oracle.com', 'https://logo.clearbit.com/oracle.com'),
('IBM', 'An American multinational technology company', 'https://www.ibm.com', 'https://logo.clearbit.com/ibm.com'),
('Adobe', 'An American multinational computer software company.', 'https://www.adobe.com', 'https://logo.clearbit.com/adobe.com');

INSERT IGNORE INTO companies (name, description, website, logo_url) VALUES
('Salesforce', 'A global leader in customer relationship management (CRM) software and cloud-based applications.', 'https://www.salesforce.com', 'https://logo.clearbit.com/salesforce.com'),
('Twitter', 'A global social media platform that enables users to send and read short 280-character messages called tweets.', 'https://www.twitter.com', 'https://logo.clearbit.com/twitter.com'),
('Snap Inc.', 'The parent company of Snapchat, a multimedia messaging app.', 'https://www.snap.com', 'https://logo.clearbit.com/snap.com'),
('Spotify', 'A global digital music service that provides streaming music, podcasts, and video content.', 'https://www.spotify.com', 'https://logo.clearbit.com/spotify.com'),
('LinkedIn', 'A professional networking site that allows users to connect, share content, and build their professional profiles.', 'https://www.linkedin.com', 'https://logo.clearbit.com/linkedin.com'),
('Adobe', 'A multinational computer software company known for its creativity and multimedia software products like Photoshop and Acrobat.', 'https://www.adobe.com', 'https://logo.clearbit.com/adobe.com'),
('Netflix', 'A global entertainment company that provides streaming video on demand, including original movies and TV shows.', 'https://www.netflix.com', 'https://logo.clearbit.com/netflix.com'),
('Zoom Video Communications', 'A provider of remote conferencing services, offering video communication and collaboration tools.', 'https://www.zoom.us', 'https://logo.clearbit.com/zoom.us'),
('Slack Technologies', 'A cloud-based collaboration platform that facilitates team communication and project management.', 'https://www.slack.com', 'https://logo.clearbit.com/slack.com'),
('GitHub', 'A web-based platform for version control and collaborative software development using Git.', 'https://www.github.com', 'https://logo.clearbit.com/github.com'),
('Pinterest', 'A social media platform used to discover, share, and organize images, ideas, and interests.', 'https://www.pinterest.com', 'https://logo.clearbit.com/pinterest.com'),
('Shopify', 'A global e-commerce platform that enables businesses to create and manage online stores.', 'https://www.shopify.com', 'https://logo.clearbit.com/shopify.com'),
('ServiceNow', 'A global IT service management company that offers cloud-based solutions for enterprise operations.', 'https://www.servicenow.com', 'https://logo.clearbit.com/servicenow.com'),
('Square', 'A provider of financial services and mobile payment solutions, including point-of-sale systems.', 'https://www.squareup.com', 'https://logo.clearbit.com/squareup.com'),
('Dropbox', 'A cloud storage provider that allows users to store and share files online.', 'https://www.dropbox.com', 'https://logo.clearbit.com/dropbox.com'),
('Atlassian', 'A software company known for its collaboration tools such as Jira, Confluence, and Trello.', 'https://www.atlassian.com', 'https://logo.clearbit.com/atlassian.com'),
('Huawei', 'A global technology company providing telecommunications equipment and consumer electronics.', 'https://www.huawei.com', 'https://logo.clearbit.com/huawei.com'),
('Alibaba Group', 'A Chinese multinational conglomerate specializing in e-commerce, retail, and technology.', 'https://www.alibaba.com', 'https://logo.clearbit.com/alibaba.com'),
('Apple', 'A multinational technology company that designs and manufactures consumer electronics and software.', 'https://www.apple.com', 'https://logo.clearbit.com/apple.com'),
('Google', 'A multinational technology company specializing in internet services, advertising technologies, and consumer electronics.', 'https://www.google.com', 'https://logo.clearbit.com/google.com');

INSERT IGNORE INTO companies (name, description, website, logo_url) VALUES
('Tata Consultancy Services', 'A leading global IT services, consulting, and business solutions organization.', 'https://www.tcs.com', 'https://logo.clearbit.com/tcs.com'),
('Infosys', 'A global leader in technology services and consulting.', 'https://www.infosys.com', 'https://logo.clearbit.com/infosys.com'),
('HCLTech', 'A global technology company helping enterprises reimagine their businesses.', 'https://www.hcltech.com', 'https://logo.clearbit.com/hcltech.com'),
('Wipro', 'A global information technology, consulting and business process services company.', 'https://www.wipro.com', 'https://logo.clearbit.com/wipro.com'),
('Tech Mahindra', 'A leading provider of digital transformation, consulting and business reengineering services.', 'https://www.techmahindra.com', 'https://logo.clearbit.com/techmahindra.com'),
('LTIMindtree', 'A global technology consulting and digital solutions company formed by the merger of L&T Infotech and Mindtree.', 'https://www.ltimindtree.com', 'https://logo.clearbit.com/ltimindtree.com'),
('Persistent Systems', 'A global company delivering digital engineering and enterprise modernization.', 'https://www.persistent.com', 'https://logo.clearbit.com/persistent.com'),
('Oracle Financial Services Software', 'A subsidiary of Oracle Corporation providing IT solutions to the financial services industry.', 'https://www.oracle.com/industries/financial-services/', 'https://logo.clearbit.com/oracle.com'),
('Coforge', 'A global digital services and solutions provider.', 'https://www.coforge.com', 'https://logo.clearbit.com/coforge.com'),
('Mphasis', 'An IT services company providing cloud and cognitive services.', 'https://www.mphasis.com', 'https://logo.clearbit.com/mphasis.com'),
('Birlasoft', 'An enterprise digital and IT services company part of the CK Birla Group.', 'https://www.birlasoft.com', 'https://logo.clearbit.com/birlasoft.com'),
('Hexaware Technologies', 'A global IT, BPO and consulting company.', 'https://hexaware.com', 'https://logo.clearbit.com/hexaware.com'),
('Zensar Technologies', 'A digital solutions and technology services company.', 'https://www.zensar.com', 'https://logo.clearbit.com/zensar.com'),
('Sonata Software', 'A global IT services company delivering innovative solutions.', 'https://www.sonata-software.com', 'https://logo.clearbit.com/sonata-software.com'),
('Cyient', 'Provides engineering, manufacturing, data analytics, and networks & operations solutions.', 'https://www.cyient.com', 'https://logo.clearbit.com/cyient.com'),
('L&T Technology Services', 'A global leader in Engineering and R&D services.', 'https://www.ltts.com', 'https://logo.clearbit.com/ltts.com'),
('Tata Elxsi', 'A design and technology services company for product engineering and solutions.', 'https://www.tataelxsi.com', 'https://logo.clearbit.com/tataelxsi.com'),
('NIIT Technologies', 'Now Coforge, an IT solutions provider focused on digital services.', 'https://www.coforge.com', 'https://logo.clearbit.com/coforge.com'),
('Mindtree', 'A global technology consulting and services company.', 'https://www.mindtree.com', 'https://logo.clearbit.com/mindtree.com'),
('KPIT Technologies', 'A global technology company specializing in IT consulting and product engineering.', 'https://www.kpit.com', 'https://logo.clearbit.com/kpit.com');

INSERT IGNORE INTO companies (name, description, website, logo_url) VALUES
('Accenture', 'A global professional services company providing consulting, technology, and outsourcing services.', 'https://www.accenture.com', 'https://logo.clearbit.com/accenture.com'),
('Capgemini', 'A global leader in consulting, technology services, and digital transformation.', 'https://www.capgemini.com', 'https://logo.clearbit.com/capgemini.com'),
('Cognizant', 'A multinational IT services company offering digital, technology, consulting, and operations services.', 'https://www.cognizant.com', 'https://logo.clearbit.com/cognizant.com'),
('IBM', 'A multinational technology company offering hardware, software, and cloud-based services.', 'https://www.ibm.com', 'https://logo.clearbit.com/ibm.com'),
('Dell Technologies', 'A multinational corporation providing IT solutions, infrastructure, and cloud services.', 'https://www.delltechnologies.com', 'https://logo.clearbit.com/delltechnologies.com'),
('SAP', 'A global software company that develops enterprise software to manage business operations.', 'https://www.sap.com', 'https://logo.clearbit.com/sap.com'),
('VMware', 'A global leader in cloud infrastructure and digital workspace technology.', 'https://www.vmware.com', 'https://logo.clearbit.com/vmware.com'),
('TCS Digital', 'The digital arm of Tata Consultancy Services providing digital transformation services.', 'https://www.tcs.com/digital', 'https://logo.clearbit.com/tcs.com'),
('DXC Technology', 'A global IT services company providing end-to-end technology solutions.', 'https://www.dxc.technology', 'https://logo.clearbit.com/dxc.technology'),
('Atos', 'A global IT services company offering solutions in digital transformation and cloud services.', 'https://www.atos.net', 'https://logo.clearbit.com/atos.net'),
('Tech Mahindra Business Services', 'A provider of customer experience and business process management services.', 'https://www.techmahindra.com/business-services', 'https://logo.clearbit.com/techmahindra.com'),
('Syntel', 'An IT services company that provides consulting and technology solutions.', 'https://www.syntelinc.com', 'https://logo.clearbit.com/syntel.com'),
('Globant', 'A technology services company specializing in AI, machine learning, and digital transformation.', 'https://www.globant.com', 'https://logo.clearbit.com/globant.com'),
('WNS Global Services', 'A leading global business process management company.', 'https://www.wns.com', 'https://logo.clearbit.com/wns.com'),
('Cognizant Technology Solutions', 'A multinational IT services company providing consulting and technology solutions.', 'https://www.cognizant.com', 'https://logo.clearbit.com/cognizant.com'),
('Virtusa', 'A global IT services company offering digital engineering and technology solutions.', 'https://www.virtusa.com', 'https://logo.clearbit.com/virtusa.com'),
('SiriusXM', 'A leader in satellite radio and streaming services, providing entertainment solutions.', 'https://www.siriusxm.com', 'https://logo.clearbit.com/siriusxm.com'),
('Elastic', 'A company that provides search-powered solutions based on Elasticsearch and other open-source technologies.', 'https://www.elastic.co', 'https://logo.clearbit.com/elastic.co'),
('Red Hat', 'A global leader in open-source software solutions, offering hybrid cloud and enterprise solutions.', 'https://www.redhat.com', 'https://logo.clearbit.com/redhat.com');


INSERT IGNORE INTO companies (name, description, website, logo_url) VALUES
('Swiggy', 'India\'s largest online food ordering and delivery platform.', 'https://www.swiggy.com', 'https://logo.clearbit.com/swiggy.com'),
('Zomato', 'A restaurant aggregator and food delivery company.', 'https://www.zomato.com', 'https://logo.clearbit.com/zomato.com'),
('Ola', 'A ride-sharing company offering transportation services.', 'https://www.olacabs.com', 'https://logo.clearbit.com/olacabs.com'),
('Paytm', 'A digital payment and financial services company.', 'https://www.paytm.com', 'https://logo.clearbit.com/paytm.com'),
('Byju\'s', 'An educational technology and online tutoring firm.', 'https://www.byjus.com', 'https://logo.clearbit.com/byjus.com'),
('Unacademy', 'An online learning platform for competitive exams.', 'https://www.unacademy.com', 'https://logo.clearbit.com/unacademy.com'),
('Razorpay', 'A payment solutions company for businesses.', 'https://www.razorpay.com', 'https://logo.clearbit.com/razorpay.com'),
('Cred', 'A platform that rewards users for paying credit card bills.', 'https://www.cred.club', 'https://logo.clearbit.com/cred.club'),
('Meesho', 'A social commerce platform enabling small businesses.', 'https://www.meesho.com', 'https://logo.clearbit.com/meesho.com'),
('PharmEasy', 'An online pharmacy and medical platform.', 'https://www.pharmeasy.in', 'https://logo.clearbit.com/pharmeasy.in'),
('Delhivery', 'A logistics and supply chain services company.', 'https://www.delhivery.com', 'https://logo.clearbit.com/delhivery.com'),
('Urban Company', 'A platform for home services and repairs.', 'https://www.urbancompany.com', 'https://logo.clearbit.com/urbancompany.com'),
('Groww', 'An investment platform for mutual funds and stocks.', 'https://www.groww.in', 'https://logo.clearbit.com/groww.in'),
('Nykaa', 'An e-commerce platform for beauty and wellness products.', 'https://www.nykaa.com', 'https://logo.clearbit.com/nykaa.com'),
('Udaan', 'A B2B e-commerce platform for small and medium businesses.', 'https://www.udaan.com', 'https://logo.clearbit.com/udaan.com'),
('Dream11', 'A fantasy sports platform for cricket and other sports.', 'https://www.dream11.com', 'https://logo.clearbit.com/dream11.com'),
('Licious', 'An online meat and seafood ordering platform.', 'https://www.licious.in', 'https://logo.clearbit.com/licious.in'),
('BigBasket', 'An online grocery delivery service.', 'https://www.bigbasket.com', 'https://logo.clearbit.com/bigbasket.com'),
('PolicyBazaar', 'An insurance aggregator and financial technology company.', 'https://www.policybazaar.com', 'https://logo.clearbit.com/policybazaar.com'),
('ShareChat', 'A social networking service supporting Indian languages.', 'https://www.sharechat.com', 'https://logo.clearbit.com/sharechat.com');

INSERT IGNORE INTO companies (name, description, website, logo_url) VALUES
('Zepto', 'A quick commerce company delivering groceries and essentials across 10 cities in India.', 'https://www.zeptonow.com', 'https://logo.clearbit.com/zeptonow.com'),
('Fi', 'A financial app offering savings accounts, mutual fund investments, and personal loans.', 'https://fi.money', 'https://logo.clearbit.com/fi.money'),
('Sprinto', 'Automates information security compliances and privacy laws for SaaS companies.', 'https://sprinto.com', 'https://logo.clearbit.com/sprinto.com'),
('Supersourcing', 'A B2B AI-enabled platform for hiring remote engineers and providing pre-vetted developers.', 'https://supersourcing.com', 'https://logo.clearbit.com/supersourcing.com'),
('GrowthSchool', 'Partners with instructors to create cohort-based courses on personal and professional growth topics.', 'https://growthschool.io', 'https://logo.clearbit.com/growthschool.io'),
('Jar', 'An automated gold savings app that allows users to save spare change and invest in digital gold.', 'https://www.myjar.app', 'https://logo.clearbit.com/myjar.app'),
('Shyft', 'A wellness and life management platform offering health, yoga, nutrition, and dermatology programs.', 'https://www.betheshyft.com', 'https://logo.clearbit.com/betheshyft.com'),
('Teachnook', 'An e-learning platform offering curated programs to help students upskill in various topics.', 'https://teachnook.com', 'https://logo.clearbit.com/teachnook.com'),
('StockGro', 'A platform aiming to educate young investors about trading and investment.', 'https://stockgro.club', 'https://logo.clearbit.com/stockgro.club'),
('BharatPe', 'A fintech startup helping small and medium-sized businesses through its digital payment platform.', 'https://bharatpe.com', 'https://logo.clearbit.com/bharatpe.com'),
('Innoviti Solutions', 'India\'s leading payment solutions company in the fintech sector.', 'https://www.innoviti.com', 'https://logo.clearbit.com/innoviti.com'),
('Rupeek', 'Provides online gold loans at your doorstep.', 'https://www.rupeek.com', 'https://logo.clearbit.com/rupeek.com'),
('Cuemath', 'An educational platform focused on making kids great at math.', 'https://www.cuemath.com', 'https://logo.clearbit.com/cuemath.com'),
('Flipkart', 'An Indian e-commerce company offering a wide range of products.', 'https://www.flipkart.com', 'https://logo.clearbit.com/flipkart.com'),
('Boat', 'A lifestyle brand dealing in fashionable consumer electronics.', 'https://www.boat-lifestyle.com', 'https://logo.clearbit.com/boat-lifestyle.com'),
('Skyroot Aerospace', 'An Indian aerospace manufacturer and commercial launch service provider.', 'https://www.skyroot.in', 'https://logo.clearbit.com/skyroot.in'),
('InMobi', 'A global provider of cloud-based intelligent mobile platforms for enterprise marketers.', 'https://www.inmobi.com', 'https://logo.clearbit.com/inmobi.com'),
('Practo', 'A health tech company that connects patients with healthcare providers.', 'https://www.practo.com', 'https://logo.clearbit.com/practo.com'),
('PhonePe', 'A digital payments and financial services company.', 'https://www.phonepe.com', 'https://logo.clearbit.com/phonepe.com'),
('Apna', 'A professional networking platform for blue and grey-collar workers.', 'https://apna.co', 'https://logo.clearbit.com/apna.co'),
('CARS24', 'An online platform for buying and selling used cars.', 'https://www.cars24.com', 'https://logo.clearbit.com/cars24.com'),
('Skillmatics', 'Creates innovative educational products and games for children.', 'https://www.skillmaticsworld.com', 'https://logo.clearbit.com/skillmaticsworld.com'),
('Rapido', 'A bike taxi platform offering transportation services.', 'https://www.rapido.bike', 'https://logo.clearbit.com/rapido.bike'),
('KreditBee', 'Provides instant personal loans to young professionals.', 'https://www.kreditbee.in', 'https://logo.clearbit.com/kreditbee.in'),
('MobiKwik', 'A digital wallet and online payment system.', 'https://www.mobikwik.com', 'https://logo.clearbit.com/mobikwik.com'),
('Xpressbees', 'A logistics company providing express delivery services.', 'https://www.xpressbees.com', 'https://logo.clearbit.com/xpressbees.com'),
('Dunzo', 'An on-demand delivery service for groceries and essentials.', 'https://www.dunzo.com', 'https://logo.clearbit.com/dunzo.com');


INSERT IGNORE INTO companies (name, description, website, logo_url) VALUES
('HDFC Bank', 'One of India\'s leading private sector banks offering a wide range of financial products and services.', 'https://www.hdfcbank.com', 'https://logo.clearbit.com/hdfcbank.com'),
('ICICI Bank', 'A major private sector bank in India providing banking and financial services.', 'https://www.icicibank.com', 'https://logo.clearbit.com/icicibank.com'),
('State Bank of India', 'India\'s largest public sector bank offering comprehensive banking services.', 'https://www.sbi.co.in', 'https://logo.clearbit.com/sbi.co.in'),
('Axis Bank', 'A prominent private sector bank in India offering a range of financial services.', 'https://www.axisbank.com', 'https://logo.clearbit.com/axisbank.com'),
('Kotak Mahindra Bank', 'A leading private sector bank in India providing banking and financial solutions.', 'https://www.kotak.com', 'https://logo.clearbit.com/kotak.com'),
('Bajaj Finance', 'A non-banking financial company offering consumer finance, SME finance, and commercial lending.', 'https://www.bajajfinserv.in', 'https://logo.clearbit.com/bajajfinserv.in'),
('Aditya Birla Capital', 'A financial services company offering a range of solutions including insurance and asset management.', 'https://www.adityabirlacapital.com', 'https://logo.clearbit.com/adityabirlacapital.com'),
('L&T Finance Holdings', 'A financial services company providing infrastructure finance, rural finance, and housing finance.', 'https://www.ltfs.com', 'https://logo.clearbit.com/ltfs.com'),
('Mahindra Finance', 'A non-banking financial company focusing on rural and semi-urban markets.', 'https://www.mahindrafinance.com', 'https://logo.clearbit.com/mahindrafinance.com'),
('Muthoot Finance', 'India\'s largest gold financing company in terms of loan portfolio.', 'https://www.muthootfinance.com', 'https://logo.clearbit.com/muthootfinance.com'),
('Manappuram Finance', 'A non-banking financial company offering gold loans and other financial services.', 'https://www.manappuram.com', 'https://logo.clearbit.com/manappuram.com'),
('Shriram Finance', 'A leading NBFC providing commercial vehicle finance, retail finance, and enterprise finance.', 'https://www.shriramfinance.in', 'https://logo.clearbit.com/shriramfinance.in'),
('Indiabulls Housing Finance', 'A housing finance company offering home loans and loan against property.', 'https://www.indiabullshomeloans.com', 'https://logo.clearbit.com/indiabullshomeloans.com'),
('PNB Housing Finance', 'A subsidiary of Punjab National Bank offering housing finance solutions.', 'https://www.pnbhousing.com', 'https://logo.clearbit.com/pnbhousing.com'),
('LIC Housing Finance', 'A subsidiary of Life Insurance Corporation of India providing housing finance.', 'https://www.lichousing.com', 'https://logo.clearbit.com/lichousing.com'),
('Can Fin Homes', 'A housing finance company promoted by Canara Bank.', 'https://www.canfinhomes.com', 'https://logo.clearbit.com/canfinhomes.com'),
('Sundaram Finance', 'A non-banking financial company offering vehicle finance and other financial services.', 'https://www.sundaramfinance.in', 'https://logo.clearbit.com/sundaramfinance.in'),
('Cholamandalam Investment and Finance Company', 'A financial services company offering vehicle finance, home loans, and SME loans.', 'https://www.cholamandalam.com', 'https://logo.clearbit.com/cholamandalam.com'),
('IDFC FIRST Bank', 'A private sector bank offering a range of financial products and services.', 'https://www.idfcfirstbank.com', 'https://logo.clearbit.com/idfcfirstbank.com'),
('Yes Bank', 'A private sector bank in India providing banking and financial services.', 'https://www.yesbank.in', 'https://logo.clearbit.com/yesbank.in');

INSERT IGNORE INTO companies (name, description, website, logo_url) VALUES
('Hindustan Unilever Limited', 'India\'s largest FMCG company offering a wide range of products in personal care, home care, and food & beverages.', 'https://www.hul.co.in', 'https://logo.clearbit.com/hul.co.in'),
('ITC Limited', 'A diversified conglomerate with significant presence in FMCG, hotels, paperboards, and agribusiness.', 'https://www.itcportal.com', 'https://logo.clearbit.com/itcportal.com'),
('Nestlé India', 'A leading nutrition, health, and wellness company with popular brands like Maggi, Nescafé, and KitKat.', 'https://www.nestle.in', 'https://logo.clearbit.com/nestle.in'),
('Britannia Industries', 'A major food company known for its biscuits, dairy products, and bakery items.', 'https://www.britannia.co.in', 'https://logo.clearbit.com/britannia.co.in'),
('Dabur India', 'A leading Ayurvedic and natural health care company with products in health supplements, personal care, and food.', 'https://www.dabur.com', 'https://logo.clearbit.com/dabur.com'),
('Marico Limited', 'A consumer goods company specializing in beauty and wellness products, including Parachute and Saffola.', 'https://www.marico.com', 'https://logo.clearbit.com/marico.com'),
('Godrej Consumer Products', 'A major player in the FMCG sector with products in personal care, hair care, and home care.', 'https://www.godrejcp.com', 'https://logo.clearbit.com/godrejcp.com'),
('Colgate-Palmolive India', 'A leading oral care company known for its toothpaste, toothbrushes, and personal care products.', 'https://www.colgatepalmolive.co.in', 'https://logo.clearbit.com/colgatepalmolive.co.in'),
('Emami Limited', 'A diversified FMCG company with brands in personal care, health care, and beauty products.', 'https://www.emamiltd.in', 'https://logo.clearbit.com/emamiltd.in'),
('Patanjali Ayurved', 'An Indian consumer goods company offering Ayurvedic products in personal care, food, and health care.', 'https://www.patanjaliayurved.net', 'https://logo.clearbit.com/patanjaliayurved.net'),
('Amul (GCMMF)', 'India\'s largest dairy cooperative known for its milk, butter, cheese, and other dairy products.', 'https://www.amul.com', 'https://logo.clearbit.com/amul.com'),
('Parle Products', 'A leading food company famous for its biscuits, confectionery, and snacks.', 'https://www.parleproducts.com', 'https://logo.clearbit.com/parleproducts.com'),
('Reckitt Benckiser India', 'A global consumer health and hygiene company with brands like Dettol, Lysol, and Harpic.', 'https://www.rb.com/in', 'https://logo.clearbit.com/rb.com'),
('Procter & Gamble India', 'A multinational consumer goods corporation with products in personal health, hygiene, and home care.', 'https://www.pgcareers.com/india', 'https://logo.clearbit.com/pgcareers.com'),
('PepsiCo India', 'A global food and beverage leader with brands like Lay\'s, Kurkure, and Tropicana.', 'https://www.pepsicoindia.co.in', 'https://logo.clearbit.com/pepsicoindia.co.in'),
('Coca-Cola India', 'A leading beverage company offering a range of soft drinks, juices, and bottled water.', 'https://www.coca-colaindia.com', 'https://logo.clearbit.com/coca-colaindia.com'),
('Tata Consumer Products', 'A consumer products company with a strong presence in beverages and food products.', 'https://www.tataconsumer.com', 'https://logo.clearbit.com/tataconsumer.com'),
('Adani Wilmar', 'A leading food company offering edible oils, rice, and other staple foods under the Fortune brand.', 'https://www.adaniwilmar.com', 'https://logo.clearbit.com/adaniwilmar.com'),
('Haldiram\'s', 'A major Indian sweets and snacks manufacturer with a wide range of traditional products.', 'https://www.haldirams.com', 'https://logo.clearbit.com/haldirams.com'),
('Cavinkare', 'An Indian conglomerate with interests in personal care, dairy, and food products.', 'https://www.cavinkare.com', 'https://logo.clearbit.com/cavinkare.com');

INSERT IGNORE INTO companies (name, description, website, logo_url) VALUES
('ICICI Lombard', 'A leading private sector general insurance company in India offering a wide range of insurance products.', 'https://www.icicilombard.com', 'https://logo.clearbit.com/icicilombard.com'),
('Tata AIA Life Insurance', 'A joint venture between Tata Group and AIA Group offering life insurance products.', 'https://www.tataaia.com', 'https://logo.clearbit.com/tataaia.com'),
('Bajaj Allianz General Insurance', 'A joint venture between Bajaj Finserv and Allianz offering a variety of general insurance products.', 'https://www.bajajallianz.com', 'https://logo.clearbit.com/bajajallianz.com'),
('Reliance General Insurance', 'A part of Reliance Capital offering a variety of general insurance products.', 'https://www.reliancegeneral.co.in', 'https://logo.clearbit.com/reliancegeneral.co.in'),
('HDFC Life Insurance', 'A leading life insurance company offering a range of life insurance and pension products.', 'https://www.hdfclife.com', 'https://logo.clearbit.com/hdfclife.com'),
('SBI Life Insurance', 'A subsidiary of State Bank of India offering life insurance products.', 'https://www.sbilife.co.in', 'https://logo.clearbit.com/sbilife.co.in'),
('Max Life Insurance', 'A joint venture between Max Financial Services and Mitsui Sumitomo Insurance offering life insurance products.', 'https://www.maxlifeinsurance.com', 'https://logo.clearbit.com/maxlifeinsurance.com'),
('New India Assurance', 'A public sector insurance company providing general insurance services across various sectors.', 'https://www.newindia.co.in', 'https://logo.clearbit.com/newindia.co.in'),
('Bharti AXA General Insurance', 'A joint venture between Bharti Enterprises and AXA Group offering a wide range of general insurance products.', 'https://www.bhartiaxa.com', 'https://logo.clearbit.com/bhartiaxa.com'),
('Star Health and Allied Insurance', 'A leading health insurance company offering a variety of health insurance plans.', 'https://www.starhealth.in', 'https://logo.clearbit.com/starhealth.in');

INSERT IGNORE INTO companies (name, description, website, logo_url) VALUES
('Birla Sun Life Insurance', 'A joint venture between Aditya Birla Group and Sun Life Financial offering life insurance products.', 'https://www.adityabirlacapital.com', 'https://logo.clearbit.com/adityabirlacapital.com'),
('Kotak Mahindra Life Insurance', 'A subsidiary of Kotak Mahindra Bank offering a wide range of life insurance products.', 'https://www.kotaklife.com', 'https://logo.clearbit.com/kotaklife.com'),
('Future Generali India Insurance', 'A joint venture between Future Group and Generali Group offering a variety of insurance products.', 'https://www.futuregenerali.in', 'https://logo.clearbit.com/futuregenerali.in'),
('ICICI Prudential Life Insurance', 'A joint venture between ICICI Bank and Prudential Corporation offering life insurance services.', 'https://www.iciciprulife.com', 'https://logo.clearbit.com/iciciprulife.com'),
('Tata Motors Finance', 'A subsidiary of Tata Motors providing vehicle financing services to customers and dealers.', 'https://www.tatamotorsfinance.com', 'https://logo.clearbit.com/tatamotorsfinance.com'),
('Magma Fincorp', 'A leading non-banking financial company offering financing solutions for vehicles, homes, and more.', 'https://www.magma.co.in', 'https://logo.clearbit.com/magma.co.in'),
('Fullerton India Credit Company', 'A non-banking financial company providing personal loans, business loans, and other financial products.', 'https://www.fullertonindia.com', 'https://logo.clearbit.com/fullertonindia.com'),
('Reliance Nippon Life Insurance', 'A subsidiary of Reliance Capital providing life insurance products and solutions.', 'https://www.reliancenipponlife.com', 'https://logo.clearbit.com/reliancenipponlife.com'),
('Sahara India Pariwar', 'A diversified conglomerate offering a wide range of financial services, including life insurance and mutual funds.', 'https://www.sahara.in', 'https://logo.clearbit.com/sahara.in'),
('HDFC Asset Management Company', 'A subsidiary of HDFC Ltd offering asset management and investment products.', 'https://www.hdfcfund.com', 'https://logo.clearbit.com/hdfcfund.com'),
('Aditya Birla Sun Life Asset Management', 'A subsidiary of Aditya Birla Group providing asset management services for mutual funds and other investment products.', 'https://www.adityabirlaamc.com', 'https://logo.clearbit.com/adityabirlaamc.com'),
('IDFC Asset Management', 'A provider of asset management and investment solutions in India.', 'https://www.idfcmf.com', 'https://logo.clearbit.com/idfcmf.com'),
('Franklin Templeton Investments', 'A global investment management firm offering mutual funds and other financial products.', 'https://www.franklintempleton.com', 'https://logo.clearbit.com/franklintempleton.com'),
('DSP Mutual Fund', 'A leading asset management company offering a wide range of mutual fund solutions.', 'https://www.dspim.com', 'https://logo.clearbit.com/dspim.com');

INSERT IGNORE INTO companies (name, description, website, logo_url) VALUES
('Paytm', 'A leading digital payments and financial services platform in India.', 'https://www.paytm.com', 'https://logo.clearbit.com/paytm.com'),
('Ola', 'A ride-hailing company that provides transportation services through its app.', 'https://www.olacabs.com', 'https://logo.clearbit.com/olacabs.com'),
('Swiggy', 'An online food delivery service that connects customers with restaurants and delivery drivers.', 'https://www.swiggy.com', 'https://logo.clearbit.com/swiggy.com'),
('Zomato', 'An online platform for discovering restaurants, ordering food, and reviewing dining experiences.', 'https://www.zomato.com', 'https://logo.clearbit.com/zomato.com'),
('Byju\'s', 'A leading edtech company offering personalized learning solutions for students.', 'https://www.byjus.com', 'https://logo.clearbit.com/byjus.com'),
('Razorpay', 'A payment gateway and fintech company offering online payment solutions to businesses.', 'https://www.razorpay.com', 'https://logo.clearbit.com/razorpay.com'),
('BigBasket', 'An online grocery delivery service providing fresh produce, household products, and more.', 'https://www.bigbasket.com', 'https://logo.clearbit.com/bigbasket.com'),
('InCred', 'A fintech company providing credit and lending solutions to individuals and businesses.', 'https://www.incred.com', 'https://logo.clearbit.com/incred.com'),
('UrbanClap', 'An online platform connecting professionals with customers for home services like cleaning, beauty, repairs, etc.', 'https://www.urbancompany.com', 'https://logo.clearbit.com/urbancompany.com'),
('PhonePe', 'A digital wallet and online payment platform offering UPI-based payments, financial services, and more.', 'https://www.phonepe.com', 'https://logo.clearbit.com/phonepe.com'),
('Dream11', 'An online fantasy sports platform offering fantasy cricket, football, and other sports.', 'https://www.dream11.com', 'https://logo.clearbit.com/dream11.com'),
('BookMyShow', 'An online ticketing platform for movies, events, and activities.', 'https://www.bookmyshow.com', 'https://logo.clearbit.com/bookmyshow.com'),
('Upstox', 'An online stock trading platform that offers investment and trading services in the stock market.', 'https://www.upstox.com', 'https://logo.clearbit.com/upstox.com'),
('Meesho', 'A social commerce platform that enables resellers to sell products online via social media.', 'https://www.meesho.com', 'https://logo.clearbit.com/meesho.com'),
('Cure.fit', 'A health and fitness company offering digital and offline services for fitness, mental wellness, and nutrition.', 'https://www.curefit.com', 'https://logo.clearbit.com/curefit.com'),
('Acko General Insurance', 'A digital-first insurance company offering motor, health, and other insurance products.', 'https://www.acko.com', 'https://logo.clearbit.com/acko.com'),
('Nykaa', 'An e-commerce platform for beauty, wellness, and fashion products.', 'https://www.nykaa.com', 'https://logo.clearbit.com/nykaa.com'),
('CarDekho', 'An online platform for buying and selling cars, along with car reviews and information.', 'https://www.cardekho.com', 'https://logo.clearbit.com/cardekho.com'),
('Giva', 'An online jewelry brand that offers a wide range of trendy silver jewelry for women.', 'https://www.giva.co', 'https://logo.clearbit.com/giva.co'),
('Oyo Rooms', 'An online platform offering affordable and quality hotel rooms across various locations.', 'https://www.oyorooms.com', 'https://logo.clearbit.com/oyorooms.com'),
('Lenskart', 'An e-commerce platform selling eyeglasses, sunglasses, and contact lenses.', 'https://www.lenskart.com', 'https://logo.clearbit.com/lenskart.com'),
('Voonik', 'An online fashion shopping platform providing a variety of clothing and accessories for women.', 'https://www.voonik.com', 'https://logo.clearbit.com/voonik.com'),
('Shuttl', 'An app-based bus service providing safe and affordable transportation for daily commuters.', 'https://www.shuttl.com', 'https://logo.clearbit.com/shuttl.com'),
('ScoopWhoop', 'A digital media company creating viral content on current events, entertainment, and lifestyle.', 'https://www.scoopwhoop.com', 'https://logo.clearbit.com/scoopwhoop.com'),
('Gaana', 'A music streaming service offering millions of songs, playlists, and radio stations.', 'https://www.gaana.com', 'https://logo.clearbit.com/gaana.com'),
('Tata Communications', 'A global telecommunications company providing services such as cloud and networking solutions.', 'https://www.tatacommunications.com', 'https://logo.clearbit.com/tatacommunications.com'),
('Tech Mahindra', 'A leading provider of digital transformation, consulting and business reengineering services.', 'https://www.techmahindra.com', 'https://logo.clearbit.com/techmahindra.com'),
('Reliance Jio', 'A telecommunications company providing 4G services and digital platforms in India.', 'https://www.jio.com', 'https://logo.clearbit.com/jio.com'),
('BharatPe', 'A fintech company offering payment solutions and lending services to businesses in India.', 'https://www.bharatpe.com', 'https://logo.clearbit.com/bharatpe.com'),
('ZestMoney', 'A fintech company offering easy and fast financing options for online and offline purchases.', 'https://www.zestmoney.in', 'https://logo.clearbit.com/zestmoney.in'),
('MobiKwik', 'A digital wallet and payment platform offering a wide range of online and offline services.', 'https://www.mobikwik.com', 'https://logo.clearbit.com/mobikwik.com'),
('Blynk', 'A platform for building and managing mobile apps for the Internet of Things (IoT).', 'https://www.blynk.io', 'https://logo.clearbit.com/blynk.io'),
('Unacademy', 'An online education platform offering live courses for competitive exams and skill development.', 'https://www.unacademy.com', 'https://logo.clearbit.com/unacademy.com'),
('Teespring', 'A print-on-demand platform that allows creators to design and sell custom apparel and merchandise.', 'https://www.teespring.com', 'https://logo.clearbit.com/teespring.com'),
('Pine Labs', 'A fintech company offering point-of-sale (POS) solutions, payment services, and lending.', 'https://www.pinelabs.com', 'https://logo.clearbit.com/pinelabs.com'),
('Tracxn', 'A research and analytics company offering data on startups and emerging technology trends.', 'https://www.tracxn.com', 'https://logo.clearbit.com/tracxn.com'),
('Vistara', 'A full-service airline in India offering premium air travel and hospitality services.', 'https://www.airvistara.com', 'https://logo.clearbit.com/airvistara.com');

INSERT IGNORE INTO companies (name, description, website, logo_url) VALUES
('Walmart', 'A multinational retail corporation that operates a chain of hypermarkets, discount department stores, and grocery stores.', 'https://www.walmart.com', 'https://logo.clearbit.com/walmart.com'),
('Amazon', 'An American multinational technology company that focuses on e-commerce, cloud computing, digital streaming, and artificial intelligence.', 'https://www.amazon.com', 'https://logo.clearbit.com/amazon.com'),
('Target', 'A retail corporation offering a wide range of products, including clothing, electronics, groceries, and more.', 'https://www.target.com', 'https://logo.clearbit.com/target.com'),
('Flipkart', 'An Indian e-commerce company that provides online shopping for electronics, apparel, and home goods.', 'https://www.flipkart.com', 'https://logo.clearbit.com/flipkart.com'),
('Snapdeal', 'An Indian e-commerce company that offers online shopping for a wide range of products including electronics, fashion, and home goods.', 'https://www.snapdeal.com', 'https://logo.clearbit.com/snapdeal.com'),
('Zara', 'A Spanish clothing and accessories retailer known for its fast fashion and affordable styles.', 'https://www.zara.com', 'https://logo.clearbit.com/zara.com'),
('H&M', 'A Swedish multinational clothing retail company known for its affordable and trendy fashion offerings.', 'https://www.hm.com', 'https://logo.clearbit.com/hm.com'),
('Forever 21', 'An American fashion retailer that offers trendy clothing, accessories, and footwear for women and men.', 'https://www.forever21.com', 'https://logo.clearbit.com/forever21.com'),
('Myntra', 'An Indian fashion e-commerce company offering a wide variety of clothing, footwear, and accessories.', 'https://www.myntra.com', 'https://logo.clearbit.com/myntra.com'),
('Lulu Group', 'A multinational conglomerate company with business operations in retail, wholesale, hospitality, and more.', 'https://www.lulugroupinternational.com', 'https://logo.clearbit.com/lulugroupinternational.com'),
('IKEA', 'A multinational furniture and home goods company offering a wide range of products for home decoration and furniture.', 'https://www.ikea.com', 'https://logo.clearbit.com/ikea.com'),
('Adidas', 'A global corporation that designs and manufactures shoes, clothing, and accessories.', 'https://www.adidas.com', 'https://logo.clearbit.com/adidas.com'),
('Nike', 'A multinational corporation that designs and manufactures sports equipment, footwear, apparel, and accessories.', 'https://www.nike.com', 'https://logo.clearbit.com/nike.com'),
('PepsiCo', 'A multinational food and beverage company known for brands such as Pepsi, Mountain Dew, Lay’s, and Tropicana.', 'https://www.pepsico.com', 'https://logo.clearbit.com/pepsico.com'),
('Coca-Cola', 'A global leader in the beverage industry known for producing non-alcoholic beverages, especially soft drinks.', 'https://www.coca-cola.com', 'https://logo.clearbit.com/coca-cola.com'),
('Nestlé', 'A multinational food and beverage company offering products in categories such as dairy, nutrition, and health science.', 'https://www.nestle.com', 'https://logo.clearbit.com/nestle.com'),
('Unilever', 'A multinational consumer goods company producing a wide range of products in health, beauty, home, and food categories.', 'https://www.unilever.com', 'https://logo.clearbit.com/unilever.com'),
('Procter & Gamble', 'A multinational consumer goods company producing health, hygiene, and home products under brands like Tide, Pampers, and Gillette.', 'https://www.pg.com', 'https://logo.clearbit.com/pg.com'),
('General Electric', 'A multinational conglomerate offering products in sectors such as energy, healthcare, and aviation.', 'https://www.ge.com', 'https://logo.clearbit.com/ge.com'),
('Siemens', 'A global technology company providing digital industries, automation, and electrification solutions.', 'https://www.siemens.com', 'https://logo.clearbit.com/siemens.com'),
('3M', 'A multinational corporation producing a wide range of products, including adhesives, abrasives, and medical devices.', 'https://www.3m.com', 'https://logo.clearbit.com/3m.com'),
('Intel', 'A multinational technology company known for designing and manufacturing microprocessors and semiconductor products.', 'https://www.intel.com', 'https://logo.clearbit.com/intel.com'),
('Qualcomm', 'A multinational corporation providing semiconductor and telecommunications equipment and services.', 'https://www.qualcomm.com', 'https://logo.clearbit.com/qualcomm.com'),
('Samsung Electronics', 'A multinational electronics company known for its smartphones, televisions, and other consumer electronics.', 'https://www.samsung.com', 'https://logo.clearbit.com/samsung.com'),
('Apple', 'An American multinational technology company known for its consumer electronics, software, and services.', 'https://www.apple.com', 'https://logo.clearbit.com/apple.com'),
('Microsoft', 'A multinational technology company offering software, electronics, and cloud computing services.', 'https://www.microsoft.com', 'https://logo.clearbit.com/microsoft.com'),
('Google', 'A multinational technology company specializing in internet-related services and products including advertising, search engines, and cloud computing.', 'https://www.google.com', 'https://logo.clearbit.com/google.com'),
('Facebook', 'A social media conglomerate that owns social platforms like Facebook, Instagram, WhatsApp, and Oculus.', 'https://www.facebook.com', 'https://logo.clearbit.com/facebook.com'),
('Twitter', 'A social media platform for microblogging and real-time news and conversations.', 'https://www.twitter.com', 'https://logo.clearbit.com/twitter.com'),
('LinkedIn', 'A professional networking platform where users can connect with colleagues, recruiters, and peers.', 'https://www.linkedin.com', 'https://logo.clearbit.com/linkedin.com'),
('Slack', 'A collaboration and communication platform offering chat, video calls, file sharing, and team management features.', 'https://www.slack.com', 'https://logo.clearbit.com/slack.com'),
('Spotify', 'A digital music streaming platform offering access to millions of songs, podcasts, and playlists.', 'https://www.spotify.com', 'https://logo.clearbit.com/spotify.com'),
('Adobe', 'A multinational software company known for its creative software products like Photoshop, Illustrator, and Acrobat.', 'https://www.adobe.com', 'https://logo.clearbit.com/adobe.com'),
('Salesforce', 'A cloud-based software company offering customer relationship management (CRM) and enterprise cloud applications.', 'https://www.salesforce.com', 'https://logo.clearbit.com/salesforce.com'),
('Zoom Video Communications', 'A video conferencing platform providing communication and collaboration solutions for businesses and individuals.', 'https://www.zoom.us', 'https://logo.clearbit.com/zoom.us'),
('Dropbox', 'A cloud-based file storage and collaboration platform that allows file sharing and synchronization.', 'https://www.dropbox.com', 'https://logo.clearbit.com/dropbox.com'),
('GitHub', 'A cloud-based platform for version control and collaboration on software development projects.', 'https://www.github.com', 'https://logo.clearbit.com/github.com');

INSERT IGNORE INTO companies (name, description, website, logo_url) VALUES
('Tesla', 'An American electric vehicle and clean energy company known for its electric cars and solar products.', 'https://www.tesla.com', 'https://logo.clearbit.com/tesla.com'),
('Ford Motor Company', 'An American multinational automaker producing cars, trucks, and electric vehicles.', 'https://www.ford.com', 'https://logo.clearbit.com/ford.com'),
('General Motors', 'An American multinational corporation producing cars, trucks, and automobile parts under brands like Chevrolet, GMC, and Cadillac.', 'https://www.gm.com', 'https://logo.clearbit.com/gm.com'),
('Toyota Motor Corporation', 'A Japanese multinational automotive manufacturer producing vehicles under brands like Toyota, Lexus, and Daihatsu.', 'https://www.toyota-global.com', 'https://logo.clearbit.com/toyota-global.com'),
('Volkswagen', 'A German automaker known for producing vehicles like the Volkswagen Golf, Polo, and the electric ID. series.', 'https://www.volkswagen.com', 'https://logo.clearbit.com/volkswagen.com'),
('Honda Motor Co.', 'A Japanese multinational conglomerate known for its automobiles, motorcycles, and power equipment.', 'https://www.honda.com', 'https://logo.clearbit.com/honda.com'),
('BMW Group', 'A German multinational company known for its luxury cars and motorcycles, including brands BMW, MINI, and Rolls-Royce.', 'https://www.bmw.com', 'https://logo.clearbit.com/bmw.com'),
('Mercedes-Benz', 'A German luxury automobile manufacturer known for its premium cars, SUVs, and commercial vehicles.', 'https://www.mercedes-benz.com', 'https://logo.clearbit.com/mercedes-benz.com'),
('Audi', 'A German automobile manufacturer specializing in luxury vehicles, part of the Volkswagen Group.', 'https://www.audi.com', 'https://logo.clearbit.com/audi.com'),
('Nissan Motor Co.', 'A Japanese multinational automobile manufacturer known for its vehicles, including electric cars like the Nissan Leaf.', 'https://www.nissan-global.com', 'https://logo.clearbit.com/nissan-global.com'),
('Hyundai Motor Company', 'A South Korean multinational automotive manufacturer known for producing affordable and reliable cars and SUVs.', 'https://www.hyundai.com', 'https://logo.clearbit.com/hyundai.com'),
('Kia Corporation', 'A South Korean automobile manufacturer producing cars, SUVs, and electric vehicles.', 'https://www.kia.com', 'https://logo.clearbit.com/kia.com'),
('Fiat Chrysler Automobiles (FCA)', 'An American-Italian multinational corporation producing vehicles under brands like Chrysler, Dodge, Jeep, and Ram.', 'https://www.fcagroup.com', 'https://logo.clearbit.com/fcagroup.com'),
('Subaru Corporation', 'A Japanese automobile manufacturer known for producing all-wheel drive vehicles, including the Subaru Outback and Forester.', 'https://www.subaru-global.com', 'https://logo.clearbit.com/subaru-global.com'),
('Peugeot', 'A French automobile manufacturer known for producing cars, vans, and electric vehicles.', 'https://www.peugeot.com', 'https://logo.clearbit.com/peugeot.com'),
('Renault', 'A French multinational automobile manufacturer known for producing cars, electric vehicles, and vans.', 'https://www.renault.com', 'https://logo.clearbit.com/renault.com'),
('Chrysler', 'An American automobile manufacturer known for producing cars, SUVs, and minivans, part of the Stellantis group.', 'https://www.chrysler.com', 'https://logo.clearbit.com/chrysler.com'),
('Jaguar Land Rover', 'A British luxury automobile manufacturer producing vehicles under the Jaguar and Land Rover brands.', 'https://www.jaguarlandrover.com', 'https://logo.clearbit.com/jaguarlandrover.com'),
('Mitsubishi Motors', 'A Japanese multinational automobile manufacturer producing cars, SUVs, and electric vehicles.', 'https://www.mitsubishi-motors.com', 'https://logo.clearbit.com/mitsubishi-motors.com'),
('Volvo Cars', 'A Swedish automobile manufacturer known for its safety features and premium cars, SUVs, and electric vehicles.', 'https://www.volvocars.com', 'https://logo.clearbit.com/volvocars.com'),
('Mazda Motor Corporation', 'A Japanese automobile manufacturer known for producing cars, SUVs, and sports cars like the Mazda MX-5.', 'https://www.mazda.com', 'https://logo.clearbit.com/mazda.com'),
('Tesla', 'An American electric vehicle manufacturer focusing on electric cars, batteries, and solar power solutions.', 'https://www.tesla.com', 'https://logo.clearbit.com/tesla.com'),
('Rivian', 'An American electric vehicle automaker producing electric trucks and SUVs with a focus on adventure and sustainability.', 'https://www.rivian.com', 'https://logo.clearbit.com/rivian.com'),
('Lucid Motors', 'An American electric vehicle manufacturer known for its luxury electric sedans, including the Lucid Air.', 'https://www.lucidmotors.com', 'https://logo.clearbit.com/lucidmotors.com'),
('Polestar', 'A Swedish electric performance car brand, jointly owned by Volvo Cars and Geely.', 'https://www.polestar.com', 'https://logo.clearbit.com/polestar.com'),
('BYD Auto', 'A Chinese automobile manufacturer known for producing electric vehicles and batteries.', 'https://www.byd.com', 'https://logo.clearbit.com/byd.com'),
('Tata Motors', 'An Indian multinational automotive manufacturer producing vehicles including Tata Nano, SUVs, and commercial vehicles.', 'https://www.tatamotors.com', 'https://logo.clearbit.com/tatamotors.com'),
('Mahindra & Mahindra', 'An Indian multinational conglomerate known for manufacturing automobiles, including SUVs, commercial vehicles, and electric vehicles.', 'https://www.mahindra.com', 'https://logo.clearbit.com/mahindra.com');

INSERT IGNORE INTO companies (name, description, website, logo_url) VALUES
('Apple', 'An American multinational technology company known for its consumer electronics, software, and digital services including the iPhone, iPad, Mac, and Apple services.', 'https://www.apple.com', 'https://logo.clearbit.com/apple.com'),
('Microsoft', 'An American multinational technology company producing software, electronics, and personal computers, known for products like Windows, Office, and Azure.', 'https://www.microsoft.com', 'https://logo.clearbit.com/microsoft.com'),
('Amazon', 'An American multinational technology and e-commerce company known for its online marketplace, cloud computing services (AWS), and consumer electronics.', 'https://www.amazon.com', 'https://logo.clearbit.com/amazon.com'),
('Google (Alphabet)', 'A global technology company known for its internet services, including search, online advertising, cloud computing, and hardware products such as Google Pixel and Google Home.', 'https://www.google.com', 'https://logo.clearbit.com/google.com'),
('Facebook (Meta)', 'A global technology conglomerate specializing in social media, virtual reality, and other digital communication platforms including Facebook, Instagram, and WhatsApp.', 'https://www.meta.com', 'https://logo.clearbit.com/meta.com'),
('Berkshire Hathaway', 'An American multinational conglomerate holding company led by Warren Buffett, known for its diverse business operations and investments in insurance, energy, manufacturing, and retail.', 'https://www.berkshirehathaway.com', 'https://logo.clearbit.com/berkshirehathaway.com'),
('Tesla', 'An American electric vehicle and clean energy company producing electric cars, batteries, and solar power solutions.', 'https://www.tesla.com', 'https://logo.clearbit.com/tesla.com'),
('Walmart', 'An American multinational retail corporation operating a chain of hypermarkets, discount department stores, and grocery stores.', 'https://www.walmart.com', 'https://logo.clearbit.com/walmart.com'),
('ExxonMobil', 'An American multinational oil and gas corporation known for exploration, production, refining, and distribution of petroleum products.', 'https://www.exxonmobil.com', 'https://logo.clearbit.com/exxonmobil.com'),
('Johnson & Johnson', 'An American multinational corporation known for its medical devices, pharmaceutical products, and consumer health products.', 'https://www.jnj.com', 'https://logo.clearbit.com/jnj.com'),
('Visa', 'A global payments technology company offering electronic payment systems and services to individuals, businesses, and governments.', 'https://www.visa.com', 'https://logo.clearbit.com/visa.com'),
('Procter & Gamble', 'An American multinational consumer goods company known for products in the segments of personal care, health care, cleaning, and consumer electronics.', 'https://www.pgb.com', 'https://logo.clearbit.com/pgb.com'),
('Coca-Cola', 'An American multinational corporation that manufactures non-alcoholic beverages, primarily known for its flagship product, Coca-Cola.', 'https://www.coca-cola.com', 'https://logo.clearbit.com/coca-cola.com'),
('JPMorgan Chase', 'An American multinational investment bank and financial services holding company.', 'https://www.jpmorganchase.com', 'https://logo.clearbit.com/jpmorganchase.com'),
('Intel Corporation', 'An American multinational corporation that designs and manufactures semiconductor chips, most famously for its computer processors.', 'https://www.intel.com', 'https://logo.clearbit.com/intel.com'),
('Oracle', 'A multinational computer technology corporation known for its database management systems, cloud computing, and enterprise software products.', 'https://www.oracle.com', 'https://logo.clearbit.com/oracle.com'),
('Alibaba Group', 'A Chinese multinational conglomerate specializing in e-commerce, retail, internet, and technology services.', 'https://www.alibaba.com', 'https://logo.clearbit.com/alibaba.com'),
('Samsung Electronics', 'A South Korean multinational conglomerate known for its consumer electronics, semiconductors, and telecommunications equipment.', 'https://www.samsung.com', 'https://logo.clearbit.com/samsung.com'),
('Chevron', 'An American multinational corporation involved in nearly all aspects of the energy sector, including oil, gas, and renewable energy sources.', 'https://www.chevron.com', 'https://logo.clearbit.com/chevron.com'),
('IBM', 'An American multinational technology company known for its innovations in computer hardware, software, artificial intelligence, and cloud computing.', 'https://www.ibm.com', 'https://logo.clearbit.com/ibm.com'),
('Pfizer', 'A multinational pharmaceutical corporation known for producing vaccines, medicines, and consumer healthcare products.', 'https://www.pfizer.com', 'https://logo.clearbit.com/pfizer.com'),
('AT&T', 'An American multinational conglomerate focused on telecommunications, media, and technology services including wireless, broadband, and entertainment.', 'https://www.att.com', 'https://logo.clearbit.com/att.com'),
('Nike', 'An American multinational corporation known for designing, manufacturing, and selling athletic shoes, apparel, and equipment.', 'https://www.nike.com', 'https://logo.clearbit.com/nike.com'),
('PepsiCo', 'An American multinational food and beverage company known for products like Pepsi, Mountain Dew, Gatorade, Tropicana, and Lay\'s chips.', 'https://www.pepsico.com', 'https://logo.clearbit.com/pepsico.com');

INSERT IGNORE INTO companies (name, description, website, logo_url) VALUES
('Apple', 'An American multinational technology company known for its consumer electronics, software, and digital services including the iPhone, iPad, Mac, and Apple services.', 'https://www.apple.com/in', 'https://logo.clearbit.com/apple.com'),
('Microsoft', 'An American multinational technology company producing software, electronics, and personal computers, known for products like Windows, Office, and Azure.', 'https://www.microsoft.com/en-in', 'https://logo.clearbit.com/microsoft.com'),
('Amazon', 'An American multinational technology and e-commerce company known for its online marketplace, cloud computing services (AWS), and consumer electronics.', 'https://www.amazon.in', 'https://logo.clearbit.com/amazon.com'),
('Google (Alphabet)', 'A global technology company known for its internet services, including search, online advertising, cloud computing, and hardware products such as Google Pixel and Google Home.', 'https://www.google.co.in', 'https://logo.clearbit.com/google.com'),
('Facebook (Meta)', 'A global technology conglomerate specializing in social media, virtual reality, and other digital communication platforms including Facebook, Instagram, and WhatsApp.', 'https://www.meta.com', 'https://logo.clearbit.com/meta.com'),
('Walmart', 'An American multinational retail corporation operating a chain of hypermarkets, discount department stores, and grocery stores.', 'https://www.walmart.com', 'https://logo.clearbit.com/walmart.com'),
('HDFC Bank', 'One of India\'s leading private sector banks offering a wide range of financial products and services.', 'https://www.hdfcbank.com', 'https://logo.clearbit.com/hdfcbank.com'),
('ICICI Bank', 'A major private sector bank in India providing banking and financial services.', 'https://www.icicibank.com', 'https://logo.clearbit.com/icicibank.com'),
('Cognizant', 'A leading global professional services company that provides IT services, consulting, and business process outsourcing.', 'https://www.cognizant.com', 'https://logo.clearbit.com/cognizant.com'),
('Tata Consultancy Services', 'A leading global IT services, consulting, and business solutions organization.', 'https://www.tcs.com', 'https://logo.clearbit.com/tcs.com'),
('Infosys', 'A global leader in technology services and consulting.', 'https://www.infosys.com', 'https://logo.clearbit.com/infosys.com'),
('Wipro', 'A global information technology, consulting and business process services company.', 'https://www.wipro.com', 'https://logo.clearbit.com/wipro.com'),
('Tech Mahindra', 'A leading provider of digital transformation, consulting and business reengineering services.', 'https://www.techmahindra.com', 'https://logo.clearbit.com/techmahindra.com'),
('Bajaj Finance', 'A non-banking financial company offering consumer finance, SME finance, and commercial lending.', 'https://www.bajajfinserv.in', 'https://logo.clearbit.com/bajajfinserv.in'),
('L&T', 'A major player in technology, engineering, construction, manufacturing, and financial services.', 'https://www.larsentoubro.com', 'https://logo.clearbit.com/larsentoubro.com'),
('Hindustan Unilever', 'A global consumer goods company in the areas of food, beverages, cleaning agents, and personal care products.', 'https://www.hul.co.in', 'https://logo.clearbit.com/hul.co.in'),
('Nestlé India', 'A subsidiary of the global food and beverage company, offering a wide range of products including dairy, nutrition, and confectionery items.', 'https://www.nestle.in', 'https://logo.clearbit.com/nestle.in'),
('PepsiCo', 'An American multinational food and beverage company known for products like Pepsi, Mountain Dew, Gatorade, Tropicana, and Lay\'s chips.', 'https://www.pepsicoindia.co.in', 'https://logo.clearbit.com/pepsico.com'),
('Reliance Industries', 'A conglomerate with businesses in petrochemicals, refining, oil, telecommunications, and retail, with a significant footprint in India and globally.', 'https://www.ril.com', 'https://logo.clearbit.com/ril.com'),
('Bharti Airtel', 'A leading global telecommunications company providing a wide range of services in India and overseas.', 'https://www.airtel.in', 'https://logo.clearbit.com/airtel.in'),
('Zomato', 'An Indian multinational restaurant aggregator and food delivery company.', 'https://www.zomato.com', 'https://logo.clearbit.com/zomato.com'),
('Flipkart', 'An Indian e-commerce company that sells a wide range of products including electronics, clothing, and groceries.', 'https://www.flipkart.com', 'https://logo.clearbit.com/flipkart.com'),
('Snapdeal', 'An Indian e-commerce company providing a variety of goods including electronics, clothing, and home items.', 'https://www.snapdeal.com', 'https://logo.clearbit.com/snapdeal.com'),
('Mahindra & Mahindra', 'An Indian multinational corporation manufacturing automobiles, motorcycles, and construction equipment.', 'https://www.mahindra.com', 'https://logo.clearbit.com/mahindra.com'),
('Ford India', 'A subsidiary of Ford Motor Company offering a wide range of vehicles including cars, SUVs, and trucks in the Indian market.', 'https://www.india.ford.com', 'https://logo.clearbit.com/ford.com'),
('Bajaj Auto', 'An Indian multinational company manufacturing two-wheelers and three-wheelers.', 'https://www.bajajauto.com', 'https://logo.clearbit.com/bajajauto.com'),
('Maruti Suzuki', 'A subsidiary of Suzuki Motor Corporation, known for producing small cars and automobiles in India.', 'https://www.marutisuzuki.com', 'https://logo.clearbit.com/marutisuzuki.com'),
('Tata Motors', 'A leading Indian multinational automobile manufacturing company producing cars, trucks, buses, and defense vehicles.', 'https://www.tatamotors.com', 'https://logo.clearbit.com/tatamotors.com'),
('Toyota India', 'A subsidiary of Toyota Motor Corporation, offering a wide range of automobiles in India, including sedans, SUVs, and hybrids.', 'https://www.toyotabharat.com', 'https://logo.clearbit.com/toyotabharat.com'),
('Audi India', 'A subsidiary of Audi AG, offering luxury automobiles in the Indian market.', 'https://www.audi.in', 'https://logo.clearbit.com/audi.in'),
('Mercedes-Benz India', 'A subsidiary of Mercedes-Benz, offering luxury cars and SUVs in the Indian market.', 'https://www.mercedes-benz.co.in', 'https://logo.clearbit.com/mercedes-benz.co.in');

INSERT IGNORE INTO companies (name, description, website, logo_url) VALUES
('Samsung Electronics', 'A South Korean multinational electronics company specializing in consumer electronics, semiconductors, and digital media technologies.', 'https://www.samsung.com/in', 'https://logo.clearbit.com/samsung.com'),
('LG Electronics', 'A South Korean multinational electronics company known for producing consumer electronics, home appliances, and mobile devices.', 'https://www.lg.com/in', 'https://logo.clearbit.com/lg.com'),
('Sony', 'A Japanese multinational corporation known for its electronics, gaming, entertainment, and financial services.', 'https://www.sony.co.in', 'https://logo.clearbit.com/sony.com'),
('Huawei', 'A Chinese multinational technology company that designs and manufactures telecommunications equipment and consumer electronics, including smartphones.', 'https://www.huawei.com/in', 'https://logo.clearbit.com/huawei.com'),
('Acer', 'A Taiwanese multinational electronics and computer hardware and software company specializing in advanced electronics technology.', 'https://www.acer.com/in', 'https://logo.clearbit.com/acer.com'),
('HP', 'An American multinational information technology company that provides hardware and software solutions including personal computers, printers, and related supplies.', 'https://www.hp.com/in', 'https://logo.clearbit.com/hp.com'),
('Dell Technologies', 'An American multinational company providing information technology solutions, including personal computers, servers, and cloud computing services.', 'https://www.dell.com/in', 'https://logo.clearbit.com/dell.com'),
('Lenovo', 'A Chinese multinational technology company that manufactures consumer electronics, personal computers, tablets, smartphones, and data center solutions.', 'https://www.lenovo.com/in', 'https://logo.clearbit.com/lenovo.com'),
('Asus', 'A Taiwanese multinational company producing computer hardware, electronics, and personal computers, including motherboards, laptops, and smartphones.', 'https://www.asus.com/in', 'https://logo.clearbit.com/asus.com'),
('Microsoft India', 'The Indian subsidiary of the global software and technology company, known for products like Windows, Office, and Azure.', 'https://www.microsoft.com/en-in', 'https://logo.clearbit.com/microsoft.com'),
('Google India', 'The Indian subsidiary of the global technology company, providing services like Google Search, YouTube, Google Maps, and Google Cloud.', 'https://www.google.co.in', 'https://logo.clearbit.com/google.com'),
('Amazon India', 'The Indian subsidiary of the global e-commerce giant, offering a wide range of products and services including cloud computing and digital streaming.', 'https://www.amazon.in', 'https://logo.clearbit.com/amazon.com'),
('Flipkart', 'An Indian e-commerce company that sells a variety of products including electronics, fashion, home goods, and groceries.', 'https://www.flipkart.com', 'https://logo.clearbit.com/flipkart.com'),
('Snapdeal', 'An Indian e-commerce company offering a wide variety of products ranging from electronics to clothing and accessories.', 'https://www.snapdeal.com', 'https://logo.clearbit.com/snapdeal.com'),
('Zomato', 'An Indian multinational restaurant aggregator and food delivery company offering restaurant search and food delivery services.', 'https://www.zomato.com', 'https://logo.clearbit.com/zomato.com'),
('Paytm', 'An Indian e-commerce payment system and financial technology company providing digital wallets, banking, and financial services.', 'https://www.paytm.com', 'https://logo.clearbit.com/paytm.com'),
('Byju\'s', 'An Indian educational technology company that offers online learning platforms and video-based learning tools for K-12 and competitive exams.', 'https://www.byjus.com', 'https://logo.clearbit.com/byjus.com'),
('Ola', 'An Indian ride-hailing company providing transportation solutions, including car and bike ridesharing services.', 'https://www.olacabs.com', 'https://logo.clearbit.com/olacabs.com'),
('Uber India', 'The Indian subsidiary of Uber Technologies, a ride-hailing company that provides transportation services using its mobile app.', 'https://www.uber.com/in', 'https://logo.clearbit.com/uber.com'),
('Swiggy', 'An Indian online food delivery service that connects customers with restaurants and food delivery partners for on-demand food delivery.', 'https://www.swiggy.com', 'https://logo.clearbit.com/swiggy.com'),
('Tata Consultancy Services', 'A global IT services and consulting company providing software solutions, business consulting, and technology services.', 'https://www.tcs.com', 'https://logo.clearbit.com/tcs.com'),
('Infosys', 'A global leader in technology services and consulting, providing IT solutions and digital transformation services for businesses.', 'https://www.infosys.com', 'https://logo.clearbit.com/infosys.com'),
('Wipro', 'A multinational corporation providing IT services, consulting, and business process outsourcing solutions.', 'https://www.wipro.com', 'https://logo.clearbit.com/wipro.com'),
('Tech Mahindra', 'A global provider of digital transformation, consulting, and business reengineering services specializing in IT and communication.', 'https://www.techmahindra.com', 'https://logo.clearbit.com/techmahindra.com'),
('Cognizant', 'A leading global professional services company that provides IT services, consulting, and business process outsourcing.', 'https://www.cognizant.com', 'https://logo.clearbit.com/cognizant.com'),
('Accenture', 'A global management consulting, technology services, and outsourcing company providing solutions to businesses worldwide.', 'https://www.accenture.com/in', 'https://logo.clearbit.com/accenture.com'),
('Capgemini', 'A multinational corporation providing consulting, technology, professional, and outsourcing services.', 'https://www.capgemini.com', 'https://logo.clearbit.com/capgemini.com'),
('HCL Technologies', 'An Indian multinational IT services and consulting company that provides software solutions, digital transformation, and IT infrastructure services.', 'https://www.hcltech.com', 'https://logo.clearbit.com/hcltech.com'),
('Birlasoft', 'A global IT services company providing enterprise digital and IT services to clients in various industries.', 'https://www.birlasoft.com', 'https://logo.clearbit.com/birlasoft.com'),
('Hexaware Technologies', 'A global IT and business process outsourcing company providing digital solutions and IT consulting services.', 'https://www.hexaware.com', 'https://logo.clearbit.com/hexaware.com'),
('Mindtree', 'A global technology consulting company providing services in digital transformation, cloud, big data, and enterprise solutions.', 'https://www.mindtree.com', 'https://logo.clearbit.com/mindtree.com'),
('L&T Infotech', 'A global technology consulting company providing IT services, digital transformation, and enterprise solutions.', 'https://www.lntinfotech.com', 'https://logo.clearbit.com/lntinfotech.com'),
('Persistent Systems', 'A global company specializing in digital engineering and enterprise modernization, providing software solutions across industries.', 'https://www.persistent.com', 'https://logo.clearbit.com/persistent.com'),
('Mphasis', 'An IT services company providing cloud and cognitive services, application management, and business process outsourcing.', 'https://www.mphasis.com', 'https://logo.clearbit.com/mphasis.com'),
('Tata Elxsi', 'A design and technology services company offering solutions in product engineering, digital transformation, and embedded systems.', 'https://www.tataelxsi.com', 'https://logo.clearbit.com/tataelxsi.com'),
('Oracle', 'A global technology company providing database software, cloud computing, and enterprise software solutions for businesses.', 'https://www.oracle.com/in', 'https://logo.clearbit.com/oracle.com'),
('Salesforce', 'A global cloud computing company providing customer relationship management software and enterprise cloud solutions.', 'https://www.salesforce.com', 'https://logo.clearbit.com/salesforce.com'),
('SAP', 'A global leader in enterprise resource planning (ERP) software and digital services, providing solutions to businesses worldwide.', 'https://www.sap.com', 'https://logo.clearbit.com/sap.com'),
('Adobe', 'A multinational software company known for products like Photoshop, Illustrator, and Adobe Acrobat for creative professionals and businesses.', 'https://www.adobe.com/in', 'https://logo.clearbit.com/adobe.com'),
('IBM', 'An American multinational technology and consulting company offering solutions in cloud computing, artificial intelligence, and blockchain.', 'https://www.ibm.com/in', 'https://logo.clearbit.com/ibm.com'),
('VMware', 'A global leader in cloud computing and virtualization technology, providing solutions for IT infrastructure, networking, and security.', 'https://www.vmware.com', 'https://logo.clearbit.com/vmware.com'),
('Red Hat', 'An American multinational software company providing open-source software products, including the Red Hat Enterprise Linux operating system.', 'https://www.redhat.com', 'https://logo.clearbit.com/redhat.com'),
('Adobe Systems', 'A global leader in multimedia and creativity software, providing solutions for content creation, digital marketing, and document management.', 'https://www.adobe.com', 'https://logo.clearbit.com/adobe.com'),
('Atlassian', 'A global software company specializing in collaboration, development, and issue-tracking software for teams.', 'https://www.atlassian.com', 'https://logo.clearbit.com/atlassian.com'),
('Slack Technologies', 'A cloud-based communication platform that provides messaging and collaboration services for teams and businesses.', 'https://www.slack.com', 'https://logo.clearbit.com/slack.com'),
('Spotify', 'A global music streaming service providing access to millions of songs, podcasts, and videos.', 'https://www.spotify.com', 'https://logo.clearbit.com/spotify.com'),
('Netflix', 'An American multinational entertainment company that provides online streaming of movies, TV shows, and original content.', 'https://www.netflix.com', 'https://logo.clearbit.com/netflix.com'),
('Disney', 'An American multinational entertainment conglomerate known for its films, television programs, and theme parks.', 'https://www.disney.in', 'https://logo.clearbit.com/disney.com'),
('Nike', 'An American multinational corporation that designs, manufactures, and sells athletic footwear, apparel, and equipment.', 'https://www.nike.com/in', 'https://logo.clearbit.com/nike.com');
