-- SQL script to populate the countries table with a comprehensive list

-- Disable foreign key checks
SET FOREIGN_KEY_CHECKS = 0;

-- Clear existing data
TRUNCATE TABLE countries;
ALTER TABLE countries AUTO_INCREMENT = 1;

-- Enable foreign key checks
SET FOREIGN_KEY_CHECKS = 1;

-- Insert statements for countries (name, code, phone_code)
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Afghanistan', 'AF', '+93');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Albania', 'AL', '+355');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Algeria', 'DZ', '+213');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Andorra', 'AD', '+376');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Angola', 'AO', '+244');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Argentina', 'AR', '+54');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Armenia', 'AM', '+374');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Australia', 'AU', '+61');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Austria', 'AT', '+43');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Azerbaijan', 'AZ', '+994');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Bahamas', 'BS', '+1');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Bahrain', 'BH', '+973');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Bangladesh', 'BD', '+880');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Barbados', 'BB', '+1');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Belarus', 'BY', '+375');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Belgium', 'BE', '+32');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Belize', 'BZ', '+501');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Benin', 'BJ', '+229');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Bhutan', 'BT', '+975');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Bolivia', 'BO', '+591');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Bosnia and Herzegovina', 'BA', '+387');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Botswana', 'BW', '+267');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Brazil', 'BR', '+55');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Brunei', 'BN', '+673');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Bulgaria', 'BG', '+359');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Burkina Faso', 'BF', '+226');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Burundi', 'BI', '+257');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Cambodia', 'KH', '+855');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Cameroon', 'CM', '+237');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Canada', 'CA', '+1');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Cape Verde', 'CV', '+238');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Central African Republic', 'CF', '+236');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Chad', 'TD', '+235');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Chile', 'CL', '+56');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('China', 'CN', '+86');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Colombia', 'CO', '+57');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Comoros', 'KM', '+269');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Congo', 'CG', '+242');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Costa Rica', 'CR', '+506');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Croatia', 'HR', '+385');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Cuba', 'CU', '+53');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Cyprus', 'CY', '+357');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Czech Republic', 'CZ', '+420');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Denmark', 'DK', '+45');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Djibouti', 'DJ', '+253');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Dominican Republic', 'DO', '+1');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Ecuador', 'EC', '+593');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Egypt', 'EG', '+20');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('El Salvador', 'SV', '+503');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Equatorial Guinea', 'GQ', '+240');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Eritrea', 'ER', '+291');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Estonia', 'EE', '+372');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Ethiopia', 'ET', '+251');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Fiji', 'FJ', '+679');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Finland', 'FI', '+358');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('France', 'FR', '+33');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Gabon', 'GA', '+241');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Gambia', 'GM', '+220');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Georgia', 'GE', '+995');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Germany', 'DE', '+49');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Ghana', 'GH', '+233');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Greece', 'GR', '+30');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Grenada', 'GD', '+1');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Guatemala', 'GT', '+502');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Guinea', 'GN', '+224');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Guinea-Bissau', 'GW', '+245');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Guyana', 'GY', '+592');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Haiti', 'HT', '+509');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Honduras', 'HN', '+504');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Hong Kong', 'HK', '+852');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Hungary', 'HU', '+36');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Iceland', 'IS', '+354');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('India', 'IN', '+91');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Indonesia', 'ID', '+62');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Iran', 'IR', '+98');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Iraq', 'IQ', '+964');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Ireland', 'IE', '+353');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Israel', 'IL', '+972');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Italy', 'IT', '+39');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Jamaica', 'JM', '+1');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Japan', 'JP', '+81');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Jordan', 'JO', '+962');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Kazakhstan', 'KZ', '+7');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Kenya', 'KE', '+254');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Kiribati', 'KI', '+686');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Kuwait', 'KW', '+965');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Kyrgyzstan', 'KG', '+996');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Laos', 'LA', '+856');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Latvia', 'LV', '+371');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Lebanon', 'LB', '+961');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Lesotho', 'LS', '+266');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Liberia', 'LR', '+231');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Libya', 'LY', '+218');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Liechtenstein', 'LI', '+423');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Lithuania', 'LT', '+370');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Luxembourg', 'LU', '+352');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Madagascar', 'MG', '+261');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Malawi', 'MW', '+265');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Malaysia', 'MY', '+60');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Maldives', 'MV', '+960');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Mali', 'ML', '+223');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Malta', 'MT', '+356');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Marshall Islands', 'MH', '+692');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Mauritania', 'MR', '+222');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Mauritius', 'MU', '+230');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Mexico', 'MX', '+52');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Micronesia', 'FM', '+691');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Moldova', 'MD', '+373');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Monaco', 'MC', '+377');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Mongolia', 'MN', '+976');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Montenegro', 'ME', '+382');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Morocco', 'MA', '+212');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Mozambique', 'MZ', '+258');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Myanmar', 'MM', '+95');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Namibia', 'NA', '+264');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Nauru', 'NR', '+674');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Nepal', 'NP', '+977');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Netherlands', 'NL', '+31');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('New Zealand', 'NZ', '+64');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Nicaragua', 'NI', '+505');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Niger', 'NE', '+227');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Nigeria', 'NG', '+234');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('North Korea', 'KP', '+850');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('North Macedonia', 'MK', '+389');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Norway', 'NO', '+47');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Oman', 'OM', '+968');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Pakistan', 'PK', '+92');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Palau', 'PW', '+680');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Palestine', 'PS', '+970');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Panama', 'PA', '+507');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Papua New Guinea', 'PG', '+675');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Paraguay', 'PY', '+595');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Peru', 'PE', '+51');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Philippines', 'PH', '+63');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Poland', 'PL', '+48');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Portugal', 'PT', '+351');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Qatar', 'QA', '+974');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Romania', 'RO', '+40');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Russia', 'RU', '+7');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Rwanda', 'RW', '+250');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Saint Kitts and Nevis', 'KN', '+1');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Saint Lucia', 'LC', '+1');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Saint Vincent and the Grenadines', 'VC', '+1');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Samoa', 'WS', '+685');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('San Marino', 'SM', '+378');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Sao Tome and Principe', 'ST', '+239');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Saudi Arabia', 'SA', '+966');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Senegal', 'SN', '+221');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Serbia', 'RS', '+381');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Seychelles', 'SC', '+248');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Sierra Leone', 'SL', '+232');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Singapore', 'SG', '+65');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Slovakia', 'SK', '+421');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Slovenia', 'SI', '+386');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Solomon Islands', 'SB', '+677');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Somalia', 'SO', '+252');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('South Africa', 'ZA', '+27');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('South Korea', 'KR', '+82');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('South Sudan', 'SS', '+211');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Spain', 'ES', '+34');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Sri Lanka', 'LK', '+94');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Sudan', 'SD', '+249');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Suriname', 'SR', '+597');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Sweden', 'SE', '+46');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Switzerland', 'CH', '+41');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Syria', 'SY', '+963');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Taiwan', 'TW', '+886');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Tajikistan', 'TJ', '+992');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Tanzania', 'TZ', '+255');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Thailand', 'TH', '+66');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Timor-Leste', 'TL', '+670');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Togo', 'TG', '+228');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Tonga', 'TO', '+676');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Trinidad and Tobago', 'TT', '+1');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Tunisia', 'TN', '+216');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Turkey', 'TR', '+90');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Turkmenistan', 'TM', '+993');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Tuvalu', 'TV', '+688');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Uganda', 'UG', '+256');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Ukraine', 'UA', '+380');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('United Arab Emirates', 'AE', '+971');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('United Kingdom', 'GB', '+44');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('United States', 'US', '+1');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Uruguay', 'UY', '+598');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Uzbekistan', 'UZ', '+998');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Vanuatu', 'VU', '+678');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Vatican City', 'VA', '+39');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Venezuela', 'VE', '+58');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Vietnam', 'VN', '+84');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Yemen', 'YE', '+967');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Zambia', 'ZM', '+260');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Zimbabwe', 'ZW', '+263');
INSERT IGNORE INTO countries (name, code, phone_code) VALUES ('Remote', 'RM', ''); 